### ISSUE TITLE
パッケージアンインストール時のトーストに表示されるパッケージ名がIDになっている

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1056]
### Description of the bug / バグの説明

https://github.com/vrc-get/vrc-get/blob/1fa0bdd68763a4008cc6c39d37655ea170ebd032/vrc-get-gui/app/projects/manage/page.tsx#L421-L430

`name: requested.pkg.display_name ?? requested.pkg.name`とすべきところが`name: requested.pkgId`となっている?

### Steps to Reproduce / 再現手順

パッケージをアンインストール

### Expected Behavior / 想定される挙動

トーストにはパッケージの名前が表示される

### Software Version / バージョン情報

0.1.7-beta.0

### OS

Windows_NT - win32 - 10.0.19045 - x86_64

**Comment by anatawa12** [comment]
package nameの情報が存在しないことがあるから一時的にそうして放置してる気がする
