### ISSUE TITLE
Existance of the VRChat Group for ALCOM ?

### ISSUE THREAD

**Issue by Spokeek** [vrc-get/vrc-get#1070]
I'm mentioning here as an issue the existance of the ALCOM VRChat Group. Unsure who is behind it, so i wondered if anyone knew about it .

[Group code ALCOM.7220](https://vrc.group/ALCOM.7220)

![image](https://github.com/vrc-get/vrc-get/assets/4519853/dac660a7-5dc4-4106-92c8-9d62e183bc4b)

**Comment by anatawa12** [comment]
I did not know that.

If someone wants, I'll crate group instead of unofficial one. I have VRC+ and space for new groups

**Comment by Spokeek** [comment]
I guess that would be cool indeed. Just, would have been nice to know who handles the group to warn them about it.

**Comment by Spokeek** [comment]
I'd be up if you create one, don't know if we should make it invite only or not.
But definitly post about it to mention that person about it

**Comment by lonelyicer** [comment]
Oh, I own this group.
Sorry for not mentioning anything related to the group here, as I was initially just trying to promote ALCOM, but wasn't sure if it was right to mention things in the issue that had nothing to do with alcom itself, so I didn't clarify the situation here for the time being
I can transfer the owner of the group to @anatawa12 if needed.

**Comment by anatawa12** [comment]
I think github discussions is good place many non-issue things so please feel free to ask about ALCOM on github discussions.

Can you transfer the ownership of the group? I'll make it as official group.

**Comment by lonelyicer** [comment]
> I think github discussions is good place many non-issue things so please feel free to ask about ALCOM on github discussions.
> 
> Can you transfer the ownership of the group? I'll make it as official group.

Okay, I'll transfer the group, but what's your VRChat ID?

**Comment by anatawa12** [comment]
My vrchat id is anatawa12 (there is link in https://anatawa12.com/).

**Comment by lonelyicer** [comment]
> Okay, I'll transfer the group, but what's your VRChat ID?

You will need to join the group before you can transfer the group owner, do you have time now?

**Comment by anatawa12** [comment]
Sorry for late. I have joined the group

**Comment by lonelyicer** [comment]
> Sorry for late. I have joined the group

I have initiated an ownership transfer to you, you need to approve

**Comment by anatawa12** [comment]
Thank you.
