### ISSUE TITLE
Android対応プロジェクトの作成/更新ができない

### ISSUE THREAD

**Issue by hic707** [vrc-get/vrc-get#1111]
### Description of the bug / バグの説明

Unity2022.3.22.f1にてAndroid対応プロジェクトの作成および更新ができません

> [!NOTE]
> Unity Hub 3.8.0により Android Build Supportがインストール済みです
> ただし、[OpenJDK]、[Android SDK & NDK Tools]は未インストールです

### Steps to Reproduce / 再現手順

# Android対応プロジェクトの作成
1.ALCOMの「UNITYを開く」よりプロジェクトを起動
2.Unityのメニュー[File]-[Build Settings...]より[Build Settings]Dlgを起動
3.Platform内のAndroidを確認する
　⇒Disableとなっており、選択しても「No Android module loaded.」となっている

# Android対応プロジェクトの更新
1.ALCOMの「UNITYを開く」よりプロジェクトを起動
　⇒確認メッセージ[^1]を表示する

[^1]: Build Target AndroidPlayer is not supported. Support for build target platform 'AndroidPlayer' is not installd. Switch to WindowsStandaloneSupport or exit Unity? [SwitchTarget] [Exit Unity]

### Expected Behavior / 想定される挙動

# Android対応プロジェクトの作成
[Build Settings]Dlg内、PlatformのAndroidがEnableとなり、[Build]ボタン、[Build And Run]ボタンがActiveになる

# Android対応プロジェクトの更新
確認メッセージなくUnityが起動する

### Software Version / バージョン情報

0.1.7

### OS

Windows 11  Pro 23H2

### Additional context / 補足

その他必要な情報などありましたらお知らせください

**Comment by anatawa12** [comment]
再現できませんでした。そのため以下の点を確認してみていただきたいです。

1. ALCOMによって認知されているUnityが使用したいUnityになっているかどうか
2. コマンドプロンプトにて`C:\Path\To\Unity.exe -projectPath C:\Path\To\AndroidProject`をALCOMによって認知されているUnityを用いて実行したときにアンドロイドプレイヤーがロードされるかどうか

**Comment by hic707** [comment]
解決できました
ありがとうございます

下記でWindowsProject、AndroidProject共に起動できることを確認しました

・原因
　同一VerのUnityが複数インストールされていたため
　(VCC経由、Unity Hub経由)
　上記のうち、Unity Hub経由でインストールしたものにのみAndroidProject対応があった
・対応
　VCC経由のものに統合(Unity Hub経由のものをアンインストール)
　VCC経由のものに対してAndroidProject対応モジュールをセットアップ

**Comment by anatawa12** [comment]
同じバージョンの Unity が複数インストールされている場合にはどちらを使用するかを ALCOM が聞くと思うのですが訊かれましたか？ もし訊かれているのであれば ALCOM の仕様として close します
