### ISSUE TITLE
VPM RepoのHeaderの追加UIと、コマンドライン引数の設定UIを揃える

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1135]
### Summary / 概要

似た操作なのにバラバラのUIになっているので、どちらかに統一する?
https://misskey.niri.la/notes/9upf9qkxtq

### Purpose / 目的

統一

### Additional context / 補足

コマンドライン引数では並び替えがサポートされている

**Comment by anatawa12** [comment]
headersの並び彼をし禁じる理由もないので並び替えできる形で揃えたいかな
