### ISSUE TITLE
"Keep Using This Version" is not i18n-ed

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1138]
https://misskey.niri.la/notes/9usxm9mj6m
![image](https://github.com/vrc-get/vrc-get/assets/61457993/e0be640d-1475-49b8-9f41-1ad0b11dd87b)

**Comment by Sayamame-beans** [comment]
このissueとは関係ないんですけど、これ、他のダイアログに比べて文と操作部分(チェックボックス)の位置近いです…?
気のせいですかね?
@anatawa12

**Comment by anatawa12** [comment]
わからん。

**Comment by anatawa12** [comment]
あけたほうがいい？

**Comment by Sayamame-beans** [comment]
なんとなくそうかも
DevToolで変えてみたけど現状のままだとこうなる見通しです
![image](https://github.com/vrc-get/vrc-get/assets/61457993/59ab1703-b2b8-4df9-8a88-070c46efff39)

**Comment by Sayamame-beans** [comment]
…これ、項目間の間隔よりは、ラジオボタンと文章、チェックボックスと文章の距離感の差、位置の違いの方が問題かも?

**Comment by anatawa12** [comment]
<img width="801" alt="image" src="https://github.com/vrc-get/vrc-get/assets/22656849/4d327ad7-020e-41ad-8f7a-35fac45e5016">


いじってみた

**Comment by Sayamame-beans** [comment]
良さそう。
