### ISSUE TITLE
起動オプションの設定画面のキャンセルボタンの配置が他のダイアログと逆?

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1142]
起動オプションの設定画面ではキャンセルが右端ですが、他のダイアログでは左端が殆どに見えます
![image](https://github.com/vrc-get/vrc-get/assets/61457993/dfc27a0e-b194-417f-aad9-d621967a2d3c)

**Comment by anatawa12** [comment]
発生しやすそうだしなんか胸痛コンポーネントを将来的には作ったほうが良さそう
