### ISSUE TITLE
バックアップの保存先を開くボタンが欲しい

### ISSUE THREAD

**Issue by mo4ca** [vrc-get/vrc-get#1169]
### Summary / 概要

バックアップの保存先を設定する画面やバックアップ作成時に保存先ディレクトリを直接開けるようなボタンが欲しい

### Purpose / 目的

現状だとエクスプローラで潜らなければ開くことができないバックアップディレクトリへのアクセスが容易になる

### Additional context / 補足

プロジェクトデータ等と違ってバックアップは直接触ることのあるものなのでアクセスが容易になるとありがたいです

**Comment by anatawa12** [comment]
Implementedin #1140
Duplicate of #1137
