### ISSUE TITLE
[GUI] ALCOM freezing in some situations

### ISSUE THREAD

**Issue by JustBuddy** [vrc-get/vrc-get#1176]
### Description of the bug / バグの説明

When specific actions are run, the ALCOM GUI will freeze.
A reload (CTRL+R) or restart is required.

### Steps to Reproduce / 再現手順

Situation 1: Deleting or removing a project.
1. Create a new Project
2. Delete that project (Both delete and remove from list) (projects and projects/manage)
3. UI will hang once completed

Situation 2: Dismissing the removal dialogue.
1. Create a new Project
2. Click the Remove project dialogue, but dont delete
3. Dismiss that delete dialogue
4. UI will hang once dismissed

Situation 3: Adding an existing project to the list.
1. Enter the "Add Existing Project" dialogue
2. UI will hang either when the project is added or the dialogue is canceled.

This only seems to affect projects.

### Expected Behavior / 想定される挙動

The UI should not hang~

### Screenshots / スクリーンショット

https://github.com/vrc-get/vrc-get/assets/8122264/ca7900ab-4b70-4c84-a662-9776b478f3d0

### Software Version / バージョン情報

0.1.8

### OS

Windows_NT - win32 - 10.0.22631 - x86_64

### Additional context / 補足

Logs upon deletion:
```
2024-06-25T22:00:57.693873+02:00 [ INFO] vrc_get_gui::commands: removing project directory: D:\Unity\Projects\_Avatar\New Project
2024-06-25T22:00:58.714809+02:00 [ INFO] vrc_get_gui::commands: removed project directory: D:\Unity\Projects\_Avatar\New Project
2024-06-25T22:00:58.967636+02:00 [ INFO] vrc_get_gui::commands: reloading settings files
2024-06-25T22:00:58.969730+02:00 [ INFO] vrc_get_gui::commands: migrating projects from settings.json
2024-06-25T22:00:58.972294+02:00 [ INFO] vrc_get_gui::commands: syncing information with real projects
2024-06-25T22:00:59.179914+02:00 [ INFO] vrc_get_gui::commands: fetching projects
```

**Comment by JustBuddy** [comment]
Checked commits
First broken: https://github.com/vrc-get/vrc-get/commit/85df60f6f3b6c352e493531546a5b987c3a99857
Last working: https://github.com/vrc-get/vrc-get/commit/7a957c1818fc5894388a899996dfec8d6d1e8f45

**Comment by JustBuddy** [comment]
Just rolling that package back to 1.0.5 didn't seem to work, though.

**Comment by anatawa12** [comment]
I reproduced that on macOS and Windows 11.

I found that `pointer-events: none;` style is unexpectedly added to html element.

**Comment by anatawa12** [comment]
upgrading dismissable-layer from 1.0.5 to 1.1.0 might cause this problem.

**Comment by anatawa12** [comment]
It looks opening dialog from popup menu is broken with the upgrade. I'm going to revert package version and file an issue to upstream soon.

**Comment by anatawa12** [comment]
I found that mixing @radix-ui/react-dismissable-layer version would cause problem.

**Comment by JustBuddy** [comment]
Well done, thanks for fixing.
