### ISSUE TITLE
ALCOMのv0.1.9がWindowsセキュリティに「重大な脅威」と認識される

### ISSUE THREAD

**Issue by Rin-A-1129** [vrc-get/vrc-get#1178]
### Description of the bug / バグの説明

既存のALCOMをv0.1.9に更新するとき、また、https://vrc-get.anatawa12.com/alcom/ の「最新版をダウンロード」からv0.1.9のALCOMをダウンロードしようとするとき、Windowsセキュリティに重大な脅威と認識される。
それによって、ALCOMの無効化、ダウンロードファイルの削除が行われる。

### Steps to Reproduce / 再現手順

１．既存のALCOMを起動し、「v0.1.9へ更新しますか？」という趣旨のポップアップで「はい」を選択する
or
２．https://vrc-get.anatawa12.com/alcom/ から、最新版のALCOMをダウンロードしようとする

### Expected Behavior / 想定される挙動

Windowsセキュリティにひっかからず、ブロックされない

### Screenshots / スクリーンショット

![image](https://github.com/vrc-get/vrc-get/assets/120964513/2669cf8c-5070-4038-b8d0-9f73d3fcbf4e)
一番下が更新の際にブロックしたという表示。残り二つがダウンロードの際に削除したという表示。

![image](https://github.com/vrc-get/vrc-get/assets/120964513/22d368a3-b725-41b8-9ab3-adb5a3740dc5)
![image](https://github.com/vrc-get/vrc-get/assets/120964513/42426745-bd22-44d8-83b6-bbeeea3d0d46)
影響を受けた項目の、個人情報を含まない部分

### Software Version / バージョン情報

0.1.9

### OS

Windows 11 Education 24H2

### Additional context / 補足

どのバージョンのALCOMから更新しようとしたか、記憶が定かではないため不明。少なくとも直近一か月以内のバージョン

プロセッサ	AMD Ryzen 7 7800X3D 8-Core Processor              4.20 GHz
実装 RAM	64.0 GB (63.1 GB 使用可能)
エディション	Windows 11 Education
バージョン	24H2
インストール日	‎2024/‎05/‎25
OS ビルド	26100.994
エクスペリエンス	Windows Feature Experience Pack 1000.26100.6.0

**Comment by anatawa12** [comment]
報告あいがとうございます。

Windows Defenderの誤判定に関しては私のできることは少ないのですが #1091 で管理しています。

ユーザによる誤判定の報告が改善に大きく影響があるため、こちらのウェブサイトで誤検知をHome Customerとして"Incorrectly detected as malware/malicious"とSecurity Intelligence Vesrionとともに報告していただけきたいです https://www.microsoft.com/en-us/wdsi/filesubmission/
