### ISSUE TITLE
Building ALCOM locally fails

### ISSUE THREAD

**Issue by JustBuddy** [vrc-get/vrc-get#1203]
### Description of the bug / バグの説明

I have the issue that I often can't get build to run, only dev.

`git clone --recurse-submodules https://github.com/vrc-get/vrc-get.git`
in vrc-get-gui -> `npm run tauri build`

It is always about the licenses, navigating there will crash dev.

What am I doing wrong?

### Steps to Reproduce / 再現手順

1. clone repo "`git clone --recurse-submodules https://github.com/vrc-get/vrc-get.git`"
2. navigate to vrc-get-gui
3. `npm run tauri build`

### Expected Behavior / 想定される挙動

It should build.

### Screenshots / スクリーンショット

![image](https://github.com/vrc-get/vrc-get/assets/8122264/6f1c8767-8f9e-4b38-95f4-2ee009ddc9a4)
or
![image](https://github.com/vrc-get/vrc-get/assets/8122264/a2521938-5a0d-4eac-a3fe-c70a01faada0)

### Software Version / バージョン情報

0.1.10-beta

### OS

Windows 11

**Comment by anatawa12** [comment]
Please try upgrading cargo about

**Comment by JustBuddy** [comment]
cargo-about isn't part of the Cargo.toml, so updating it apparently wont work, only installing it would.

**Comment by JustBuddy** [comment]
I ran `cargo install --locked cargo-about` outside my project directory, and it now seems to build.
How would I have known about this if you didn't tell me?
Won't the project I try to build specify the version it needs if it depends on it?

**Comment by anatawa12** [comment]
ALCOM is depending on the latest version of cargo about and rust currently and there's no specific version ALCOM is depending on.
I didn't write about this in any documentation so I'll document this.

I've planned to leave cargo about in the future since many futures in cargo about is not necessary for this project.
