### ISSUE TITLE
AppImage版において、設定の読み込みよりも先に画面遷移が行われる (SPAとして動作せずページのロードが毎回挟まる)

### ISSUE THREAD

**Issue by YTJVDCM** [vrc-get/vrc-get#1213]
### Description of the bug / バグの説明

AppImage版ALCOMにおいて、画面遷移が行われた際、設定情報(テーマ、言語等)が読み込まれる前に画面遷移が発生し、一瞬だけウィンドウがデフォルトの設定状態で表示される。
(また、バージョン表示が一瞬`vLoading...`表記になる)
ソースから直接`npm run tauri dev` した場合では発生せず、手元でAppImageビルドした場合では発生、
またArch Linux, Debian 12(Docker)の両者で発生したため、AppImage固有の問題と思われる。

### Steps to Reproduce / 再現手順

1. AppImage版においてALCOMを起動し、画面遷移を含む操作(プロジェクト管理画面への移動、設定画面への移動等)を行う
1. 一瞬だけ表示が規定の状態(英語・ライトテーマ等)になる

### Expected Behavior / 想定される挙動

画面遷移時に言語やテーマといった情報が読み込まれた後に画面表示が行われるべきである

### Screenshots / スクリーンショット

https://github.com/vrc-get/vrc-get/assets/50657624/6f8fe15f-500f-4432-afc9-f760d6e03b05

### Software Version / バージョン情報

0.1.9

### OS

Arch Linux x86_64 kernel 6.9.6-arch1-1, Debian 12 x86_64 (Docker)

**Comment by anatawa12** [comment]
そもそも規定動作ではページ推移時にHTMLやカラーテーマ等の読み込みが発生しない(SPAとして動作する)ので、それが発生すること自体がバグですね。

トーストが表示されてるときにページ推移するとトーストが消えますか？(SPAとして動作しないことの確認をしたいです)

webkitgtkのhisotry apiがうごかないとかでnextjsのSPA動作が切れるのかな...

**Comment by YTJVDCM** [comment]
一旦既存プロジェクト追加でトースト表示時の動作を確認したところ、トースト表示も消えました

**Comment by KisaragiEffective** [comment]
> Arch Linux, Debian 12(Docker)の両者

Debian 12 (Host) でも再現

**Comment by KisaragiEffective** [comment]
(0.1.11でも一応検証→再現)

**Comment by anatawa12** [comment]
appimageというより、webkitgtkとtauriのブリッジの実装に起因しそうなことがわかりました。

どうやらlinux環境だと`.txt`の`Content-Type`が損刺ししなくなり、この結果としてnext.jsが意図しないファイルを読んだと誤解してハードリロードが発生してるっぽいです。
