### ISSUE TITLE
プロジェクト削除でファイルも削除する場合には二重確認したい

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1261]
### Summary / 概要

タイトル通りです。
若干怖いので二重確認にしたい感じがします。

### Purpose / 目的

事故防止強化

**Comment by anatawa12** [comment]
何重確認すりゃええんやってなってくる気もする

あとゴミ箱から戻せるからそこまでいるか？という気もしていて

**Comment by Sayamame-beans** [comment]
そういえばそうだった
じゃあ…まあ無くても良いかも

**Comment by anatawa12** [comment]
win/macos/linuxのAPI的にできるのか知らないけど、消したときのトーストに戻すボタンを生やすことは検討してもいいかもしれない？other issue

**Comment by anatawa12** [comment]
とりあえずゴミ箱で消えないので close as not plannned にします
