### ISSUE TITLE
初期設定時の設定内容が後から変更可能なことを個別にではなく全体的に纏めて示す

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1264]
であれば、個別に書くよりどこかに固定で載せておいた方が良いような気もしたり…?
個別に書くと、書いてないところはそうじゃないように見えますし、かといって全部書くとしつこいと思うので

_オリジナルは @Sayamame-beans が https://github.com/vrc-get/vrc-get/pull/1214#discussion_r1668571046 にポスト_

**Comment by Sayamame-beans** [comment]
画面の隅とかに常に書いていくとか、冒頭で一回書いて後は触れないとかが私の案です(日本語は後者でとりあえずやってます)

**Comment by anatawa12** [comment]
setup:appearance:description で "ここで行う初期設定の内容は後からでも変えることができます。"って触れてるから、ほかから消してもいいのかも知っれない？

**Comment by Sayamame-beans** [comment]
そうかも。
