### ISSUE TITLE
設定ページにない警告や説明分が初期設定時にだけある

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1265]
この辺り、設定ページにない警告や説明分が初期設定時にだけあるのに少し違和感あり…?

_オリジナルは @Sayamame-beans が https://github.com/vrc-get/vrc-get/pull/1214#discussion_r1676819877 にポスト_

**Comment by anatawa12** [comment]
具体的にどれを指してる？すべて？

**Comment by Sayamame-beans** [comment]
バックアップの保存形式の説明とかパス系の警告とかその辺りを意図してたはず

**Comment by anatawa12** [comment]
バックアップの保存形式の説明とパス系の警告は移植しました
