### ISSUE TITLE
VRCプロジェクトにおける互換バージョン同士のアップグレードなら、migrationの方のダイアログにしたい

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1267]
VRCプロジェクトにおける互換バージョン同士のアップグレードなら、migrationの方のダイアログにしたい感じもします。
(本文を細工することは出来ますが、タイトル部分は変えられないので)

_オリジナルは @Sayamame-beans が https://github.com/vrc-get/vrc-get/pull/1246#discussion_r1677020387 にポスト_

**Comment by anatawa12** [comment]
やっぱその方が良い？そうするか
