### ISSUE TITLE
ユーザーパッケージ画面の改善

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1268]
選択出来る感(項目としての主張?)が若干弱い気がします
![image](https://github.com/user-attachments/assets/019232fb-dee5-46f7-9bce-65cec2beff1a)

_オリジナルは @Sayamame-beans が https://github.com/vrc-get/vrc-get/pull/1222#issuecomment-2226926881 にポスト_

**Comment by anatawa12** [comment]
<img width="402" alt="image" src="https://github.com/user-attachments/assets/9fa66c55-3768-47ae-a496-aa073a13f7de">

こんな感じ？

**Comment by Sayamame-beans** [comment]
現状よりは良さそう…
