### ISSUE TITLE
ALCOM更新時、インストール場所が強制的にデフォルトの場所になってしまう

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1320]
### Description of the bug / バグの説明

いつからか分かりませんが(かなり以前から?)、ALCOMを更新した場合、インストール時に指定した場所ではなく、`(略)/AppData/Local/ALCOM`にインストールされてしまいます。旧バージョンは初めに指定した場所に留まります。

発見当初はvrc-get-guiが取り残されていたため、途中からALCOMに変更されたことによる弊害かと思いましたが、ALCOM同士(0.1.9→0.1.12)でも同様の現象が発生したためインストーラーのバグ(upstream issue)の可能性があるかもしれません。

### Steps to Reproduce / 再現手順

1. ALCOMの旧バージョンを、インストール場所を指定した上でインストールする。
2. 更新ダイアログに従って更新する。
3. 以前のバージョンが残されており、更新されたバージョンは別の場所に存在する。

### Expected Behavior / 想定される挙動

指定したインストール場所で更新されるべきです

### Software Version / バージョン情報

0.1.12 (5a6fa31cc0925c6b5ea900033cffd5acf20d0658)

### OS

Windows 10.0.19045 - x86_64

### Additional context / 補足

追記: これによる影響として、スタートメニューへのピン留め等も若干おかしくなる可能性がありそうです

**Comment by Sayamame-beans** [comment]
ALCOMからアップデートを実行した際のインストーラーの画面
![image](https://github.com/user-attachments/assets/c3620570-3cbb-4319-bb21-2114d93a7d0e)

なお、アンインストール時は指定した場所が正しく認識されているため、アンインストールを行うと二重に入った内の最初に入れた方とショートカット類が消えます。
また、何故かAppData以下にある方のuninstall.exeも消えますが、AppData以下にある方のALCOM.exeだけは取り残されます。(直接起動すると正常に実行可能)

(off-topic: もしかしてmalware扱いされるのって正常にアンインストール出来ないこのバグのせいだったりしますか?)

**Comment by Sayamame-beans** [comment]
(これ、仮に修正出来たとして、状況を修正するための手を打つのが微妙に厄介そうで悩み)

**Comment by anatawa12** [comment]
#1291 の影響かも

upstreamのバグではなくalcomのバグだけど対処法ない

正直won't fixしたい

**Comment by anatawa12** [comment]
いろんな問題の対処でnsisスクリプト自体を独自化するのを少し考えてるのでそのときに対処します

**Comment by Sayamame-beans** [comment]
> #1291 の影響かも

ふむ。次回の更新で覚えてたら確認してみますね。
