### ISSUE TITLE
表示されないtooltipがある

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1323]
日本語と英語で確認
対象:
https://github.com/vrc-get/vrc-get/blob/dba937c72189b072948c23d64e2e16193219631d/vrc-get-gui/locales/en.json5#L200-L201

**Comment by Sayamame-beans** [comment]
https://github.com/vrc-get/vrc-get/blob/dba937c72189b072948c23d64e2e16193219631d/vrc-get-gui/locales/en.json5#L165-L166
https://github.com/vrc-get/vrc-get/blob/dba937c72189b072948c23d64e2e16193219631d/vrc-get-gui/locales/en.json5#L168
なども表示されていないようです

**Comment by Sayamame-beans** [comment]
manage projectページは対策が入ったようですが、issue初めに入っているvpm repositoriesのtooltipの方は大丈夫そうですか?

**Comment by anatawa12** [comment]
そっちはそもそも該当箇所がなくなってる

**Comment by Sayamame-beans** [comment]
あら…?
じゃあ不要キーだったのです…? (気付いてなかった)
