### ISSUE TITLE
fallback用のキーであるため各言語側で削除可能な項目がある

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1326]
fallbackしなくて良い(片方に揃えて良い)じゃんって話をどこかでした気がします
https://github.com/vrc-get/vrc-get/blob/dba937c72189b072948c23d64e2e16193219631d/vrc-get-gui/app/(main)/settings/page.tsx#L553-L554

**Comment by anatawa12** [comment]
fallbackはしていいんだけど(もういらなくなった記憶あるけど)、英語からは消して良い

**Comment by Sayamame-beans** [comment]
全ての言語でsettings:use vcc～の方があったので、fallback自体消しても良さそうな感じはありますね
