### ISSUE TITLE
Kasperskyでウイルス判定される

### ISSUE THREAD

**Issue by AtrasWorld** [vrc-get/vrc-get#1347]
### Description of the bug / バグの説明

ALCOM0.1.12くらいからKasperskyでウイルス判定される。
インストール段階ですでに判定を食らい、インストール後のアプリも判定を食らう。
現在は除外設定をしている。

イベント: 悪意のあるオブジェクトが検知されました
ユーザー: AW-AMD-MAIN\AtrasWorld
ユーザー種別: アクティブなユーザー
アプリケーション名: smartscreen.exe
アプリケーションのパス: C:\Windows\System32
コンポーネント: ファイル保護
結果の説明: 検知
名前: UDS:DangerousObject.Multi.Generic
精度: 完全一致
危険性: 高
オブジェクト種別: ファイル
オブジェクト名: ALCOM_0.1.13_x64-setup.exe
オブジェクトのパス: C:\Users\AtrasWorld\AppData\Local\Temp\Rar$EXa8348.6389.rartemp
MD5: FB1740969716B51D8BB649C38CD583D7
理由: クラウドプロテクション

### Steps to Reproduce / 再現手順

インストール時、ウイルス判定される

### Expected Behavior / 想定される挙動

ウイルス判定されない

### Software Version / バージョン情報

0.1.13

### OS

Windows11Pro

### Additional context / 補足

カスペルスキーインターネットセキュリティ
本体及び定義は最新

**Comment by anatawa12** [comment]
マルウェア対策ソフト系は #1091 でトラックしています(タイトルが悪かったので先ほど修正しました)

基本的にあまり作者側でできることがないためKasperkyに誤判定であることをレポートしていただきたいです。

**Comment by anatawa12** [comment]
Duplicate of #1091
