### ISSUE TITLE
Fail to run dev ALCOM

### ISSUE THREAD

**Issue by JustBuddy** [vrc-get/vrc-get#1389]
### Description of the bug / バグの説明

When trying to build ALCOM, I get the following error:
```
warning: `vrc-get-gui` (bin "ALCOM") generated 3 warnings (run `cargo fix --bin "ALCOM"` to apply 3 suggestions)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 2m 06s
thread '<unnamed>' panicked at src\interface\rust\desktop.rs:86:63:
called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "Das System kann die angegebene Datei nicht finden." }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
The german translates to "System can't find specified file".

Stacktrace:
```
stack backtrace:
   0:     0x7ffc2657b23d - napi_register_module_v1
   1:     0x7ffc260b3f59 - <unknown>
   2:     0x7ffc265584e1 - napi_register_module_v1
   3:     0x7ffc26580586 - napi_register_module_v1
   4:     0x7ffc2657fe4a - napi_register_module_v1
   5:     0x7ffc2657fa01 - napi_register_module_v1
   6:     0x7ffc26580908 - napi_register_module_v1
   7:     0x7ffc265807c7 - napi_register_module_v1
   8:     0x7ffc2658070f - napi_register_module_v1
   9:     0x7ffc265806f8 - napi_register_module_v1
  10:     0x7ffc26b23ff4 - napi_register_module_v1
  11:     0x7ffc26b244f0 - napi_register_module_v1
  12:     0x7ffc26773c9b - napi_register_module_v1
  13:     0x7ffc26773213 - napi_register_module_v1
  14:     0x7ffc2679068e - napi_register_module_v1
  15:     0x7ffc26576ebd - napi_register_module_v1
  16:     0x7ffcfecf257d - BaseThreadInitThunk
  17:     0x7ffd0100af28 - RtlUserThreadStart
```

### Steps to Reproduce / 再現手順

1. Clone current repository.
2. git clone --recurse-submodules https://github.com/JustBuddy/vrc-get.git (My repos up to date with yours, no changes)
3. in vrc-get-gui: npm run tauri dev

### What I tried ###
- Starting from a fresh repo clone.
- Using rustup to update rust components.

### Expected Behavior / 想定される挙動

It should compile

### Screenshots / スクリーンショット

![image](https://github.com/user-attachments/assets/1aafde3e-794b-4581-91e3-347fe9496637)

### Software Version / バージョン情報

0.1.14 (current master)

### OS

Windows 11 Pro 23H2

**Comment by anatawa12** [comment]
it looks related to tauri-apps/tauri#10550 and will be fixed when tauri cli 2.0.0-rc.4 is released.

Could you try installing tauri-cli from dev branch with `cargo install --git https://github.com/tauri-apps/tauri tauri-cli` and use `cargo-tauri run dev` instead of `npm run tauri dev`?

**Comment by JustBuddy** [comment]
> it looks related to [tauri-apps/tauri#10550](https://github.com/tauri-apps/tauri/pull/10550) and will be fixed when tauri cli 2.0.0-rc.4 is released.
> 
> Could you try installing tauri-cli from dev branch with `cargo install --git https://github.com/tauri-apps/tauri tauri-cli` and use `cargo-tauri run dev` instead of `npm run tauri dev`?

This seems to work, the command is `cargo-tauri dev`

**Comment by Spokeek** [comment]
> This seems to work, the command is cargo-tauri dev

I confirmed that this resolved a blocking build i had. I also had to **reinstall the latest version of rust** Windows binaries to update `rustc`

**Comment by anatawa12** [comment]
ALCOM is constantly upgrading MSRV to latest rust so requireing reinstalling (or simply upgrading with rustup) is expected.
