### ISSUE TITLE
No UI on MacOS Mojave

### ISSUE THREAD

**Issue by LIVE4MINT** [vrc-get/vrc-get#1399]
### Description of the bug / バグの説明

Broken UI on fresh install of MacOS Mojave

### Steps to Reproduce / 再現手順

i just installed ALCOM and Unity Hub and issue just exists anyways

### Expected Behavior / 想定される挙動

Expected to see actual UI

### Screenshots / スクリーンショット

https://pasteboard.co/d5K1wkJtHFM4.png

### Software Version / バージョン情報

latest that was avaliable at August 18 2024

### OS

macOS 10.14.6

### Additional context / 補足

On older versions it showed UI for a second and then it shows black screen

**Comment by anatawa12** [comment]
AFAIK, macOS Catalina is compatibile with all macs compatible with Mojave so could you let me know why you're still using mojave?

**Comment by LIVE4MINT** [comment]
> AFAIK, macOS Catalina is compatibile with all macs compatible with Mojave so could you let me know why you're still using mojave?

i use mojave because its the last one that was able to run 32x and 64x apps and catalina run only 64x on intel macs and i have some software that was not updated but there was no replacement made

**Comment by anatawa12** [comment]
I understand you want to use x86 apps.

I tried to support mojave in #1404 so could you try CI version of ALCOM can be downloaded from https://github.com/vrc-get/vrc-get/actions/runs/10485549802?pr=1404?
Please click and download universal-apple-darwin, extract the zip, mount disk image at `bundle/dmg/ALCOM_0.1.15-beta.0_universal.dmg` and run `ALCOM.app` in the dmg.
(`ALCOM` at root of zip and `bundle/macos/ALCOM.app` will not working because zip file doesn't preserve unix file permissions, which is required for applications.)

It will not be signed executable so you have to allow executing unsigned binary in `System Settings.app`.

**Comment by LIVE4MINT** [comment]
> I understand you want to use x86 apps.
> 
> I tried to support mojave in #1404 so could you try CI version of ALCOM can be downloaded from https://github.com/vrc-get/vrc-get/actions/runs/10485549802?pr=1404? Please click and download universal-apple-darwin, extract the zip, mount disk image at `bundle/dmg/ALCOM_0.1.15-beta.0_universal.dmg` and run `ALCOM.app` in the dmg. (`ALCOM` at root of zip and `bundle/macos/ALCOM.app` will not working because zip file doesn't preserve unix file permissions, which is required for applications.)
> 
> It will not be signed executable so you have to allow executing unsigned binary in `System Settings.app`.

<img width="1280" alt="Снимок экрана 2024-08-23 в 19 58 07" src="https://github.com/user-attachments/assets/94e82e5a-0ff1-414a-b4bf-cfff006f1a2f">
 i got this error after was able to configure stuff at first launch (but config screen was visible only half in middle and parts on top and bottom covered in gray rectangle)

**Comment by anatawa12** [comment]
Thank you for trying. Could you find some error from browser console that can be opened with cmd+shift+c? @LIVE4MINT

**Comment by LIVE4MINT** [comment]
> Thank you for trying. Could you find some error from browser console that can be opened with cmd+shift+i? @LIVE4MINT

so i tried to open browser console but seems like as it is not a full browser in build and as i tried all combinations from "developer" tab that only visible in safari so i have no access to anything here, maybe there is any other ways?

**Comment by anatawa12** [comment]
with CI builds of ALCOM, it should be possible to open devtools with cmd opt i. Could you try this?

**Comment by anatawa12** [comment]
I have added error page to show more error info in #1457 and merged to #1404 so could you try new version? You should see new error page with detailed info

**Comment by LIVE4MINT** [comment]
> I have added error page to show more error info in #1457 and merged to #1404 so could you try new version? You should see new error page with detailed info

so i tried to run 1457 and it gave me black screen with "Loading..." on top left corner (that disappeared after a while), i didnt found 1404 but i found 1406 (im not frequent user of github) and it gave me ui but it was endless loading and nothing clickable(after a while it just became gray gradient without any text)

also i tried 1465 and it gave same result as 1457

**Comment by anatawa12** [comment]
Sorry for unclear instructions. I improved error message window in 1457 and it's now included in 1404.
So, please try 1404 and please show me the error message shown.
If you do same thing as comment above (https://github.com/vrc-get/vrc-get/issues/1399#issuecomment-2307473937), it's expected to be error messages shown.

Build from PR #1404 can be downloaded from this link: https://github.com/vrc-get/vrc-get/actions/runs/10644858400?pr=1404

**Comment by LIVE4MINT** [comment]
it gave this text:


Client-side unrecoverable error occurred
This must be a bug! Please report this bug!
Report Issue
Error Message:
ReferenceError: Can't find variable: ResizeObserver
Stack Trace:
tauri://localhost/_next/static/chunks/23-282f354df7675c4d.js:1:12071
aW@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73243
aH@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73304
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73743
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74330
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74330
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74330
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74330
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74330
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73767
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73767
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73767
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73767
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73767
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730

**Comment by anatawa12** [comment]
Thank you! I have added another code to try supporting Mojave. Could you try again?

New build link: https://github.com/vrc-get/vrc-get/actions/runs/10672104228?pr=1404

**Comment by LIVE4MINT** [comment]
> https://github.com/vrc-get/vrc-get/actions/runs/10672104228?pr=1404

there was like ms of some ui then this:


Client-side unrecoverable error occurred
This must be a bug! Please report this bug!
Report Issue
Error Message:
ReferenceError: Can't find variable: ResizeObserver
Stack Trace:
tauri://localhost/_next/static/chunks/23-282f354df7675c4d.js:1:12071
aW@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73243
aH@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73304
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73743
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74330
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74330
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74330
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74330
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74330
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73767
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73767
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73767
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73767
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73767
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:74403
a9@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:84632
aY@tauri://localhost/_next/static/chunks/fd9d1056-98e1b47241f2a0d5.js:1:73730

**Comment by anatawa12** [comment]
Sorry, I missed the way to apply polyfill. Could you try with newer build?

https://github.com/vrc-get/vrc-get/actions/runs/10672439541?pr=1404

**Comment by LIVE4MINT** [comment]
so it works partially but colors strange sometimes and settings is not scrollable https://pasteboard.co/yCoRqNg79wGt.png
https://pasteboard.co/5ypFluOceOCB.png

**Comment by anatawa12** [comment]
Umm.. it looks tons of features in css missing in Safari bundled in 10.14 so it's too hard to support macOS 10.14 fully....

I need some developer using that safari and advanced skills but I don't have.

**Comment by anatawa12** [comment]
Unfortunately, I decided to only support newer version of macOS in ALCOM so I'm closing this issue.
I'm sorry to not support your platform.

If you are familiar with command line, you still can use vrc-get as a VPM Client.
vrc-get doesn't have specific policy for version support but I think there are very limited reason to drop older versions so I think you can use much longer.
