### ISSUE TITLE
ExFATのディスク上で io error: No such file or directory (os error 2) が発生する

### ISSUE THREAD

**Issue by yabumi823** [vrc-get/vrc-get#1402]
### Description of the bug / バグの説明

macOS環境においてExFATでフォーマットされたディスクが接続されている。
このディスク上に存在するUnity projectにおいて、vrc-getでパッケージを更新/削除しようとすると`io error: No such file or directory (os error 2)`というエラーが発生し、パッケージを更新/削除することができない。

### Steps to Reproduce / 再現手順

1. ExFATでフォーマットされたディスク上に、任意のUnity projectを作成する
2. 作成したUnity projectに、任意のパッケージをインストールする
3. インストールされているパッケージ(VRChat SDKを含む)を更新・ダウングレードまたは削除しようとするとエラーが発生する

### Expected Behavior / 想定される挙動

パッケージの更新・ダウングレード・削除が正常に行われるべき

### Software Version / バージョン情報

vrc-get 1.8.1

### OS

macOS Sonoma 14.5

### Additional context / 補足

- APFSまたはMac OS拡張フォーマットのディスク上では症状が発生しないことを確認済み。
  - パッケージのインストールに限ってはExFATフォーマットのディスク上でも可能。更新または削除でのみ症状が発生する。
- 実際の検証にはALCOM v0.1.14を使用してプロジェクト作成などの作業を実施。症状そのものはALCOM / vrc-get-cliのどちらで操作しても発生することを確認済み。

**Comment by anatawa12** [comment]
macOS Sonoma 14.4.1 on M1 Max MBPでは今確認したところExFATのdisk imageでは再現しませんでした。
物理イメージは今から準備します。

**Comment by anatawa12** [comment]
調査したところ、リソースフォーク等を保持する`._`から始まるファイルの扱いがうまく行っていない模様でした。

**Comment by anatawa12** [comment]
#1403 で修正を試みました。CIで生成されたバージョンを試していただきたいです。

**Comment by anatawa12** [comment]
#1403 で修正を試みました。 https://github.com/vrc-get/vrc-get/actions/runs/10484281817?pr=1403 こちらからダウンロードできるCIで生成されたバージョンを試していただきたいです。

テストには上記リンクにて `universal-apple-darwin` をダウンロードし展開し、その中にある`bundle/dmg/ALCOM_0.1.15-beta.0_universal.dmg` にの中にある `ALCOM.app` を使用してください。
(`bundle/macos/ALCOM.app`と`ALCOM`はunix permissionsがzipファイルでは保持されない仕様によりテストに使用できません)

また、これらのファイルは署名されていないためSystem Settings.appにて署名されていないファイルの実行を許可して上げる必要がある可能性があります。

**Comment by yabumi823** [comment]
> #1403 で修正を試みました。

上記のバージョン(ALCOM v0.1.15-beta.0+5239dff)で動作確認を行い、症状が改善したことを確認しました。

ExFAT, APFS, MacOS拡張フォーマットの物理ボリュームそれぞれに対してプロジェクトを作り検証。
いずれの場合も問題なくパッケージのインストール・アップグレード・ダウングレード・削除が行えました。

ご対応いただきありがとうございました🙏
