### ISSUE TITLE
unity一覧の更新機能

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1408]
### Summary / 概要

現在、ALCOMはUnity一覧の更新機能が無かったと記憶しています。
それは恐らく https://github.com/vrc-get/vrc-get/issues/593#issuecomment-2199369919 であるように数秒掛かってしまうためだと認識しているのですが、手動更新を行うボタンであればそれでも問題無いかと考えています。
現状、一覧を更新するためにALCOMを再起動するのはやや面倒だと思うので、一覧を更新するボタンがあれば良いなと思います。(インストール誘導の画面にも追加する?)

### Purpose / 目的

利便性をやや強化

### Additional context / 補足

そもそも、VCCと異なりインストール時にUnityの導入を誘導しないため、Unityのインストールは手動でやらなければならないかのような印象を与えている可能性があります。それは望ましいことではないと思います。
(新規ユーザーの視点で考えると、ALCOMをセットアップし、プロジェクトを新規作成し、それから開こうとして初めてUnityの導入が誘導されることになるためです)
追加していないのは、前述の通り一覧の取得に数秒掛かってしまうためだとは思うのですが、(v1.0.0にするならば)そちらの方ももう少し改善案を考えたい気持ちがあります。

セットアップ後にバックグラウンドで確認して1つも無ければサイドバーに警告を出す、とかは思いついた妥協案の1つですが、セットアップから離れてしまった後になるので気付きづらそうですね。

**Comment by anatawa12** [comment]
`get_unity_from_unity_hub`を呼び出して`VccDatabaseConnection`に保存すればいいので一応good firstつけときます
