### ISSUE TITLE
ALCOMのログファイルの保存場所を開くボタンが欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1419]
### Summary / 概要

ALCOMのログを共有するのに、どこに保存してあるかとなって厄介です。
ログページの右上とかにボタンを配置すると良さそうです。

### Purpose / 目的

ALCOMのログ共有をしやすいように

**Comment by anatawa12** [comment]
settingsのALCOMにもあってよさそう

**Comment by Sayamame-beans** [comment]
(ログの中に保存場所が書いてあるのはそうですね)

**Comment by Sayamame-beans** [comment]
> settingsのALCOMにもあってよさそう

それは他のコンフィグの保存場所とかの話につながるので別issue書きます
というかもうあると思いこんでました
