### ISSUE TITLE
resolveあとにenv version mismatch起きるかも

### ISSUE THREAD

**Issue by anatawa12** [vrc-get/vrc-get#1423]
### Description of the bug / バグの説明

resolveあとにenv version mismatch起きるかも

### Steps to Reproduce / 再現手順

1. VCC開く
2. 5分程待つ
3. resolveする
4. パッケージの操作する

### Expected Behavior / 想定される挙動

mismatchしない

### Software Version / バージョン情報

未検証

### OS

N/A

### Webview Version / Webviewバージョン

N/A

**Comment by Sayamame-beans** [comment]
可能であればenvironment mismatchのトーストに情報追加したいですね
今はこれ出てもどうしたら良いか分からないので

**Comment by anatawa12** [comment]
とりあえずinternal errorッテ明示した
