### ISSUE TITLE
Ability to export and import all repos currently installed

### ISSUE THREAD

**Issue by BenjiThatFoxGuy** [vrc-get/vrc-get#1458]
### Summary / 概要

The ability to export and import all repos currently present in alcom's config. Preferably to some human readable format (i.e. JSON) but that's not a necessity. Said export of all repos could then be put into version control, and in case one of the parties collaborating on the project is missing some repos - they can pass ALCOM that file to import any missing repos they might have.

### Purpose / 目的

I collaborate on some VRC projects, I also sometimes work from different computers. Git solves most of my issues, but sometimes there's new repos that I add that I immediately start using on one of the machines and that means the other machines will fail to resolve the related VPM packages because they lack the repos. It would be nice to keep those repos in sync by the means of importing an export from the machine that added that repo to the project.

**Comment by anatawa12** [comment]
<img width="1326" alt="image" src="https://github.com/user-attachments/assets/6040dcaa-869a-4336-95c1-53fbb47d466a">

There already is export / import repository list implemented in #1209 (issue #643).
Is this lacks feature?

**Comment by BenjiThatFoxGuy** [comment]
Oh! My ALCOM hasn't notified me of the update, so I didn't have the issue. If it exports/imports the repos altogether with the headers, I'm going to close this issue. Sorry.

**Comment by BenjiThatFoxGuy** [comment]
Okay it appears to not export headers. I'm going to open a new issue then. Thank you for clarifying.

**Comment by BenjiThatFoxGuy** [comment]
I opened #1459 to make it more clear instead of reusing this FR.
