### ISSUE TITLE
Ability for the import/export repo list feature to include headers.

### ISSUE THREAD

**Issue by BenjiThatFoxGuy** [vrc-get/vrc-get#1459]
### Summary / 概要

Currently the import/export of repo lists in ALCOM does not take into consideration headers for any repos that might be utilizing them.

### Purpose / 目的

There are teams that collaborate on VRChat worlds, for Jams and such and I believe if they utilize headers to authorize access to internal VPM repos - they would appreciate this addition.

### Additional context / 補足

Maybe the ability to omit exporting headers while exporting the repo list, for security reasons when you don't need it would be a good idea too.

**Comment by anatawa12** [comment]
exporting repository is degined to include headers so this should be marked as bug

**Comment by anatawa12** [comment]
Umm... As far as I tested know, exporting headers works...

**Comment by BenjiThatFoxGuy** [comment]
i've just checked my machines and for some reason headers disappeared from one repo that had it, on all 3 (macos, windows, windows). i don't know what caused it but i'll have to readd the repo then. i'll report back if it happens again.

**Comment by JustBuddy** [comment]
I had a similar issue, it turned out that for unknown reasons the header data got removed out of the settings.json, so ALCOM can't export those.

Try removing and adding the repos again and see if it works for you

**Comment by BenjiThatFoxGuy** [comment]
what's strange is the repo kept working as-is, despite settings.json not containing the headers (the header check was done at cloudflare level so it should've hard failed). but yeah i'll have to readd it, thanks!

**Comment by anatawa12** [comment]
Actually, header settings will also exists in repository local cache so it might be removed from settings.json but kept in repository local cache.

**Comment by anatawa12** [comment]
If losting headers in settings is caused by ALCOM, please file another issue.
