### ISSUE TITLE
プロジェクト管理画面でプロジェクト名の代わりにパスが表示されてしまっている

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1478]
### Description of the bug / バグの説明

タイトル通りです。
パスを二度繰り返す必要はないので、上にあるのは恐らくプロジェクト名であるはずです。

originally found in: https://twitter.com/gizmo_ds/status/1829051509251916152

### Steps to Reproduce / 再現手順

1. 任意のプロジェクト管理画面を開く

### Expected Behavior / 想定される挙動

プロジェクト名が表示される

### Screenshots / スクリーンショット

![image](https://github.com/user-attachments/assets/a14e73ff-fa6c-4933-ad4b-ab100a15c692)

### Software Version / バージョン情報

0.1.14

### OS

Windows 10 Pro 22H2

**Comment by anatawa12** [comment]
Windowsで\を対応できてないなこれはさては

**Comment by anatawa12** [comment]
#1484 で治ってますか

**Comment by Sayamame-beans** [comment]
直ってそうでした
