### ISSUE TITLE
「Webview Version / Webviewバージョン」について、「この情報はALCOMの設定画面にあります。」とありますが、無い気がする

### ISSUE THREAD

**Issue by Narazaka** [vrc-get/vrc-get#1480]
### Description of the bug / バグの説明

タイトル通り、issueの入力欄にそのような記述があるが、ない気がする。

### Steps to Reproduce / 再現手順

設定画面を開いて探す

### Expected Behavior / 想定される挙動

Webview Version / Webviewバージョンがどこかにあるべき

### Screenshots / スクリーンショット

![image](https://github.com/user-attachments/assets/39268ebb-28dc-43ad-b9f7-d031cda98238)

### Software Version / バージョン情報

0.1.14

### OS

Windows 10 Pro 22H2

**Comment by anatawa12** [comment]
現在未リリースですね。リリースするまで表示しないほうが良かったかな

**Comment by anatawa12** [comment]
0.1.15リリースしました
