### ISSUE TITLE
Ctrl+Fで出てくる検索窓を出したあとで、アプリ全体が一時的に操作不能になる時がある

### ISSUE THREAD

**Issue by Narazaka** [vrc-get/vrc-get#1481]
### Description of the bug / バグの説明

Ctrl+Fで出てくる検索窓を出して英字で単語を入力し検索したりした後に、どこかクリックしたりすると操作を受け付けなくなるときがある。

他のウインドウをアクティブにしてから戻ってくると解消している。

### Steps to Reproduce / 再現手順

設定画面でCtrl+Fで出てくる検索窓を出して英字で単語を入力し検索したりした後に、どこかクリックしたりする

ただし条件がいまいち不明で狙って再現が出来ない。
検索窓付近をクリックすると起こる気がするが定かでない。

都合2回ほど起こった

### Expected Behavior / 想定される挙動

うごく

### Software Version / バージョン情報

v0.1.14

### OS

Windows 10 Pro 22H2

**Comment by anatawa12** [comment]
ctrl + fで検索窓が出てくるんです?そっちが意図した動作じゃないですね

**Comment by Narazaka** [comment]
![image](https://github.com/user-attachments/assets/29d4b802-5518-4b1b-b68c-4206547f1fa9)
出ますね普通に
スタイルもあたってるので意図的なやつかと思ってましたが違うのか

**Comment by anatawa12** [comment]
これWebView2が勝手に出してますね。スタイルも多分WebView2(WinUI系列かな)のやつですね。(macOSだと出てこない)

便利な場面はありそうですがとりあえずこれ自体はclose as not plannedで、検索が出ることを別issueとします。
