### ISSUE TITLE
ALCOMからVRC Quick Launcherを起動できるようにしてほしい

### ISSUE THREAD

**Issue by kesera2** [vrc-get/vrc-get#1486]
### Summary / 概要
既存のIssueにないようでしたので起票させていただきました。
表題の通り、ALCOMからVRC Quick Launcherを起動できるようになると嬉しいです。
ご検討いただけますと幸いです。

### Purpose / 目的

VCCからALCOMに移行した人がVRC Quick Launcherの起動方法に困らないようになるかと思います。また、ALCOMを開いているときに、VRC Quick Launcherを開きたい場合、一度VCCを開く必要があるので、その手間も減らせるはずです。

### Additional context / 補足

デフォルトのVRC Quick Launcherのファイルパスは以下になります。
> C:\Users\%username%\AppData\Local\Programs\VRChat Creator Companion\Tools\VRC Quick Launcher\VRC Quick Launcher.exe

**Comment by Sayamame-beans** [comment]
VCCがないケースを想定するなら自作するのも方向性としてはあり得るかなと思ったりもします

**Comment by anatawa12** [comment]
https://github.com/vrchat-community/creator-companion/issues/140 が解決してくれるような気もする

自作はメンテ的に私はやりたくないなぁ...

**Comment by kesera2** [comment]
たしかにVRC Quick LauncherがVCCに依存しているのが問題ですね...。
個別にインストールできるようになればこの問題は解決できそうですので、このIssueはCloseしていただいて大丈夫です！
ご検討ありがとうございました！
