### ISSUE TITLE
Oh no! The Unity China Edition "2022.3.22f1c1" is not supported!

### ISSUE THREAD

**Issue by lolosiax** [vrc-get/vrc-get#1515]
### Description of the bug / バグの説明

When using VCC, I was able to bypass version detection by adding my own way to use "2022.3.22f1c1", but ALCOM was unable to display any screen at all.
The reason for using "2022.3.22f1c1" is that Unity's enterprise in China Mainland will try to block us from downloading "2022.3.22f1" and automatically redirect us to "2022.3.22f1c1".
Downloading "2022.3.22f1" is too cumbersome, and "2022.3.22f1c1" is still available on VCC, so I'm still using "*f1c1" version.

### Steps to Reproduce / 再現手順

Open the ALCOM and wait for the main window to display.

### Expected Behavior / 想定される挙動

show my projects.

### Screenshots / スクリーンショット

![image](https://github.com/user-attachments/assets/67ce6ce1-93fd-45ab-ba80-46b7be62280b)
![image](https://github.com/user-attachments/assets/8b564944-2ee7-4451-b57f-0f45ff499858)

### Software Version / バージョン情報

0.1.15 (eb5c2ca120a2a8dea3634811272160868427c096)

### OS

Windows 10.0.22631 - x86_64

### Webview Version / Webviewバージョン

128.0.2739.67

**Comment by KisaragiEffective** [comment]
This might happen cli too...
The definition does not look like f and c can be appeared at same version: https://github.com/vrc-get/vrc-get/blob/9a1d5e9cdd1b959a2eebd8e5294169c8448f4caf/vrc-get-vpm/src/version/unity_version.rs#L18-L24

**Comment by anatawa12** [comment]
Thank you for bug report!

I'm surprised with the version name "2022.3.22f1c1".

According to [unity version numbers section in this unity docs](https://docs.unity3d.com/2022.3/Documentation/Manual/ScriptCompilationAssemblyDefinitionFiles.html#unity-version-numbers), china version of unity will form "2022.3.22c1" so ALCOM(vrc-get) recognizes project based on this.

> adding my own way to use "2022.3.22f1c1"


Is there anything special for adding unity? Is "2022.3.22f1c1" original version name of unity or deceive version name to foolish VCC?

**Comment by TheSmileCat** [comment]
Yes, I've downloaded Unity over the years, and I've downloaded many different versions, but it's always "*f1c1".
![image](https://github.com/user-attachments/assets/2c097171-ebaa-485a-a634-a4c370a4edd2)

**Comment by TheSmileCat** [comment]
In fact, there is another problem. I don't know why, ALCOM can't automatically identify the UnityHub installed in the system. I manually selected the installation location. Is it because "-c6" causes the problem that cannot be identified?

**Comment by anatawa12** [comment]
Oh... documentation is incorrect (or I read incorrectly).

I'll add support for 22f1c1.

> In fact, there is another problem. I don't know why, ALCOM can't automatically identify the UnityHub installed in the system. I manually selected the installation location. Is it because "-c6" causes the problem that cannot be identified?

ALCOM is currently detecting unity hub installation by registry keys and default unity hub path came from [docs](https://docs.unity3d.com/hub/manual/HubCLI.html) but it looks everything are different fo china version.

https://github.com/vrc-get/vrc-get/blob/9a1d5e9cdd1b959a2eebd8e5294169c8448f4caf/vrc-get-vpm/src/environment/unity_management.rs#L177-L201

Could you let me know the default install path and/or registry key for unity hub detection?

**Comment by TheSmileCat** [comment]
It looks like `\HKEY_LOCAL_MACHINE\SOFTWARE\Unity Technologies\Hub\InstallLocation` not `InstallPath`
![image](https://github.com/user-attachments/assets/e9a9b996-fb8f-4deb-b31e-cb02afc93617)

**Comment by anatawa12** [comment]
it looks install location itself are same so exe name can be different. could you let me know exe name of unity hub?

**Comment by lonelyicer** [comment]
I think it should be clear in the setup screen that users should be directed to download the normal version of unity hub and not the Chinese version of unity hub.
Here is link: [https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe](https://public-cdn.cloud.unity3d.com/hub/prod/UnityHubSetup.exe)

**Comment by lonelyicer** [comment]
The Chinese version of unity hub cannot download and install the normal version of unity, only the Chinese version of unity, i.e. version number `20**. *. *f*c*.`

**Comment by TheSmileCat** [comment]
> it looks install location itself are same so exe name can be different. could you let me know exe name of unity hub?
It's `Unity Hub.exe`, sha1 or sha256 sign is `优三缔科技（上海）有限公司`.
![image](https://github.com/user-attachments/assets/acd544f5-b899-4607-9096-85a63475798d)

**Comment by Yimn** [comment]
Hi，I'm meeting the same problem in macOS.
<img width="1300" alt="image" src="https://github.com/user-attachments/assets/c9623b68-494b-4673-ac92-36a3a2dd9a4b">

**Comment by anatawa12** [comment]
I came up with one question: How f1c1 versions store project unity version?
 
 in `ProjectSettings/ProjectVersion.txt` there is unity version the project is made with and ALCOM reads that for selecting unity for opening project.

Could you send me ProjectVersion.txt in your project with china edition of unity?

**Comment by TheSmileCat** [comment]
> Could you send me ProjectVersion.txt in your project with china edition of unity?

[ProjectVersion.txt](https://github.com/user-attachments/files/17106202/ProjectVersion.txt)

**Comment by Yimn** [comment]
[ProjectVersion.txt](https://github.com/user-attachments/files/17106298/ProjectVersion.txt)
```
m_EditorVersion: 2022.3.22f1
m_EditorVersionWithRevision: 2022.3.22f1 (887be4894c44)
```

**Comment by anatawa12** [comment]
Thank you. It looks the unity version saved in `ProjectVersion.txt` will also say it's china version of unity.

Did you see some editor version mismatch warning on opening unity projects with `2022.3.22f1` (not `c1`) with `2022.3.22f1c1`?
If so, we may edit `ProjectVersion.txt` or provide china version of template projects......

**Comment by lolosiax** [comment]
Yes, when I used VCC to create the project with version '2022.3.22f1', it gave me a warning when I first opened it. "Last time it was with another version of Unity. Go ahead or cancel, "is roughly what it says.

> Although the VRC SDK panel will also display A line `wrong version, please use '2022.3.22f1'` in the background, it is ignored because it does not affect the use.

**Comment by anatawa12** [comment]
I have created patch to support f1c1 releases of Unity : #1558.

Could you try this version and let us know if works?

**Comment by lolosiax** [comment]
Where should I get the binary distribution (*.exe) for this version? For example, Google Drive or somewhere else?
Obviously, letting me compile this project myself might be an unattainable task for me.

**Comment by anatawa12** [comment]
you can get ci builds of ALCOM.

![image](https://github.com/user-attachments/assets/c9299d64-3ea2-4328-bd8a-1c6b2ed9ab61)

open the pull request, select checks tab and click Build GUI. this will open CI details page.

![image](https://github.com/user-attachments/assets/2123d28d-dd63-4b70-8409-99b7d20818d4)


And then you can get exe (and installer and others) from Artifacts section.
depending on your platform, please select from universal-apple-darwin, x86_64-pc-windows-msvc or 
x86_64-unknown-linux-gnu

**Comment by lolosiax** [comment]
![QQ20241001-234010](https://github.com/user-attachments/assets/4a92a511-6759-42a6-8f75-a44eca5340a6)
When it first started, it still failed to automatically recognize Unity Hub.

This time, ALCOM is working without any unexpected problems on the main screen.

When I created a new project, it selected the f1 version as usual, and when I subsequently tried to open the project, the program just gave me an error "... f1 version does not exist ", failed to tell me that I need to switch to the system installed f1c1 version. Like providing a button or telling me how to do it。

I then found that I could manually switch versions in the drop-down box, and this time the project opened successfully.

![QQ20241002-000310](https://github.com/user-attachments/assets/71e9daef-3899-40e7-8782-e86372ee5cbb)
Apparently, it mistakenly gave me a text "used old version", suggested to display the text "Consider using international version for more stable support" when detecting the Chinese version, and "used old version" only if the Chinese version is not the latest version of the corresponding VCC either.

**Comment by anatawa12** [comment]
> When it first started, it still failed to automatically recognize Unity Hub.

Thank you and sorry I forgot about that.

> When I created a new project, it selected the f1 version as usual, and when I subsequently tried to open the project, the program just gave me an error "... f1 version does not exist ", failed to tell me that I need to switch to the system installed f1c1 version. Like providing a button or telling me how to do it

It's expected for now, but I will add suggestion soon.

> Apparently, it mistakenly gave me a text "used old version", suggested to display the text "Consider using international version for more stable support" when detecting the China version, and "used old version" only if the China version is not the latest version of the corresponding VCC either.

Good catch. I'll remove or change the warning for the patch version mismatch.

**Comment by anatawa12** [comment]
> It looks like \HKEY_LOCAL_MACHINE\SOFTWARE\Unity Technologies\Hub, key is InstallLocation not InstallPath

I found that my installation also use InstallLocation. That was my old mistake. thank you

**Comment by anatawa12** [comment]
Thank you for previous test.
According to your testing, it looks basic (backend) support of china version is good enough.
Therefore I just upgraded china version support with:

- Fixed false-positive unity patch migration warning with 2022.3.22f1c1
- Allowing to use f1c1 version for unity migration like 2019 => 2022 or 2022.3.6f1(c1) => 2022.3.22f1(c1)
- Added suggestion to use international version of unity
- Asking for switch between china and international version on opening unity if we can find the other version.

Could you test again?

**Comment by lolosiax** [comment]
> I fixed The USE CHINA VERSION UNITY button won't close the dialog when clicked, even if Unity is already open. in the latest build (build is in progress).

It just pops up the Notification "opening Unity", not the previous dialog, and no Unity is opened, no project version changed.  
It's blocked in `Loading Unity from Unity Hub took few tens of seconds.` and `unityEditors` is a empty array in `setting.json`.  
Restarting is not valid  

version `v0.1.16-beta.0+2debc9a`.

**Comment by lolosiax** [comment]
```
Windows PowerShell
版权所有（C） Microsoft Corporation。保留所有权利。

安装最新的 PowerShell，了解新功能和改进！https://aka.ms/PSWindows

PS D:\Program Files\Unity Hub> cmd
Microsoft Windows [版本 10.0.22631.4169]
(c) Microsoft Corporation。保留所有权利。

D:\Program Files\Unity Hub>".\Unity Hub.exe" -- --headless editors -i

D:\Program Files\Unity Hub>
2021.3.18f1c1 , installed at D:\Program Files\Unity\2021.3.18f1c1\Editor\Unity.exe
2019.4.31f1c1 , installed at D:\Program Files\Unity\2019.4.31f1c1\Editor\Unity.exe
2022.3.22f1c1 , installed at D:\Program Files\Unity\2022.3.22f1c1\Editor\Unity.exe
2023.2.11f1c1 , installed at D:\Program Files\Unity\2023.2.11f1c1\Editor\Unity.exe
2022.3.17f1c1 , installed at D:\Program Files\Unity\2022.3.17f1c1\Editor\Unity.exe
_      (The cursor is blocked here)
```
It looks like Unity Hub is blocked here, and it's not quitting. But I'm not quite sure if I'm using the right command.

**Comment by anatawa12** [comment]
With powershell, it's hard to check if unity hub is exited because powershell come to prompt just after launching exe, even if command line mode. (if the exe has gui flag).

Actually, the 2nd `D:\Program Files\Unity Hub>` line tell us that powershell thinks unity hub is already exited (or something like that), while stdout is still on the console and unity hub outputs some text to the console.
(sorry i'm not good at this weird shell behavior in windows.)

**Comment by Misaka-L** [comment]
> With powershell, it's hard to check if unity hub is exited because powershell come to prompt just after launching exe, even if command line mode. (if the exe has gui flag).
> 
> Actually, the 2nd `D:\Program Files\Unity Hub>` line tell us that powershell thinks unity hub is already exited (or something like that), while stdout is still on the console and unity hub outputs some text to the console. (sorry i'm not good at this weird shell behavior in windows.)

actually he is using `cmd.exe`: `PS D:\Program Files\Unity Hub> cmd`

**Comment by lolosiax** [comment]
I restarted my computer. This time it keeps getting errors, It's not blocking anymore.
```
failed to update unity from unity hub: Unity Hub failed to get installed unity versions
```

Please give me a Unity Hub startup parameter you are using. I will use terminal to check stdout.

No, the Powershell section above is actually redundant, I just switched to CMD

**Comment by anatawa12** [comment]
> actually he is using cmd.exe: PS D:\Program Files\Unity Hub> cmd

Sorry but even with `cmd.exe` same thing happens on windows.

> Please give me a Unity Hub startup parameter you are using. I will use terminal to check stdout.

`editors` `-i` is all.


https://github.com/vrc-get/vrc-get/blob/e4ae8fa148dbd24609730c91b5155ca6d2ace7a5/vrc-get-vpm/src/unity_hub.rs#L26

**Comment by lolosiax** [comment]
> I fixed The USE CHINA VERSION UNITY button won't close the dialog when clicked, even if Unity is already open. in the latest build (build is in progress).  
Yes, it was successfully fixed.  
I'm ignoring the failure to load the version for now. I found that Unity opened properly after failing to load, but I couldn't open Untiy if ALCOM was loading.

**Comment by anatawa12** [comment]
Umm...

The Unity Hub app will live like daemon / service (we call differently depending on OS) so I come up with there is possibility that if the unity hub launched from ALCOM is the first launch of Unity Hub in your login session, the Unity Hub launched with ALCOM become daemon / service.
Could you try manually launching Unity Hub before launching ALCOM after restart / re-login?

**Comment by anatawa12** [comment]
Anyway, this issue is for china version of unity support, and It looks Unity Hub problem is different problem so I'm going to merge the china version support and close this issue, and I want to discuss unity hub load problem in another issue.

**Comment by lolosiax** [comment]
OK, this is indeed a new problem, and it is not appropriate to continue here, while the Chinese version of the problem seems to have been solved.

**Comment by lolosiax** [comment]
> You can download newer version of unitypackage or you may replace with VCC version distributed at https://vpm.gatosyocora.net/.

I managed to bundle the newly upgraded 2019 project and indeed the original author fixed the issue.
