### ISSUE TITLE
セットアップ時、Unity Hubのインストールチェックに失敗する

### ISSUE THREAD

**Issue by YTJVDCM** [vrc-get/vrc-get#1534]
### Description of the bug / バグの説明

初回セットアップ時、Unity Hubがインストールされていない環境下においても、Unity Hubのインストールを促すメッセージが表示されず、存在しないUnityのパスが選択された状態でセットアップが進行する

### Steps to Reproduce / 再現手順

1. (既にALCOMの設定ファイルが存在する場合) macOS/Linuxでは `~/.local/share/VRChatCreatorCompanion/vrc-get/gui-config.json` 、Windowsの場合は多分 `%LOCALAPPDATA%\VRChatCreatorCompanion\vrc-get\gui-config.json` (未検証)を消す
2. (インストールされている場合) Unity Hubをアンインストール
3. ALCOMを起動
4. "Unity Hubの設定"の項目で、"Unity Hubが見つかりませんでした"のメッセージが表示されないままセットアップが進行する

![Screenshot_20240917_004331](https://github.com/user-attachments/assets/c388a39f-5312-47c4-8c0b-a736395b684d)

### Expected Behavior / 想定される挙動

本来であれば下記のように、"UnityHubが見つかりませんでした。"のメッセージが表示され、Unity Hubのインストールページへのボタンが表示されるはず
(画像は`page.tsx`を書き換えて無理やり表示させたもの)
![Screenshot_20240917_004435](https://github.com/user-attachments/assets/62ac4141-f3b5-4442-a3be-ddce7de6327b)

### Screenshots / スクリーンショット

上記に記載

### Software Version / バージョン情報

v0.1.15

### OS

Debian 12 x86_64, macOS 12.7.6 Monterey

### Webview Version / Webviewバージョン

2.44.3 (Linux), 17613.3.9.1.16 (macOS)

### Additional context / 補足

おそらくUnityHubがインストールされていない場合でもUnity Hubのインストール先としては既定値のパスが入っている(undefinedではない)ため、`vrc-get-gui/app/(setup)/setup/unity-hub/page.tsx`の`hubInstalled`が常にtrueになってしまっていそうな感じがする。 (未検証)

**Comment by YTJVDCM** [comment]
Mac/Linux固有の不具合っぽい...?

**Comment by anatawa12** [comment]
![image](https://github.com/user-attachments/assets/8d36ca1c-acba-4e7a-b5cd-1853c42e9d02)

```sh
pacman -R unityhub
cd ~/.local/share
mv VRChatCreatorCompanion VRChatCreatorCompanion.bak
```

で再現しないです

今再現手段で気づいたんですけど unity hubはVCCと共有してるのでsettings.jsonなのでこれがリセットされてないのが原因かも

**Comment by YTJVDCM** [comment]
あーほんとだ...`settings.json`も消したらそっちの表示出るようになりました...お騒がせしました。
(再現ケースが特殊な気もしますが、一応記載の条件で問題自体は発生はするためクローズするかはお任せします...)

**Comment by anatawa12** [comment]
設定されてたらそれが指定されるのは規定動作なので良しとします
