### ISSUE TITLE
resolveが必要な状態のパッケージを手動追加しようとした際に、ダイアログが空にならないようにする

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1563]
### Summary / 概要

from: https://misskey.niri.la/notes/9ytxqcri5t
> vpm-manifest.jsonに情報があるパッケージがpackage-lock.jsonにないケース(resolve neededなケース)において、当該パッケージを直接インストールしようとしたら、ダイアログにパッケージ情報が何も出ないまま

> 入れ直しをする時は「～をインストール」が出るから、少なくとも直接指定では出して良い気はする

### Purpose / 目的

利便性向上
より直感的に

**Comment by anatawa12** [comment]
調べた感じディレクトリだけ残ってる場合に発生するっぽい
