### ISSUE TITLE
"missing field `Verison`"のエラーが出てしまいプロジェクト、ならびに「設定」が開けない

### ISSUE THREAD

**Issue by tai-cha** [vrc-get/vrc-get#1590]
### Description of the bug / バグの説明

"missing field `Verison`"のエラーが出てしまいプロジェクト、「設定」が開けなくなっています

### Steps to Reproduce / 再現手順

ALCOMを開いたら突然
VCCをアプデしたかもしれないぐらいしか心当たりがない

### Expected Behavior / 想定される挙動

プロジェクトが開ける

### Screenshots / スクリーンショット

↓ どのプロジェクトも同じように開けない
![image](https://github.com/user-attachments/assets/4f9f01ac-f914-462f-b911-1d2e98cfcd07)
↓設定も参照できない
![image](https://github.com/user-attachments/assets/95840558-a926-445f-bdcd-d575e08c0f5c)

↓ ログ画面
![image](https://github.com/user-attachments/assets/56ba9622-f92e-4371-b43d-6fb050e58cfa)

### Software Version / バージョン情報

0.1.15

### OS

Windows 11 Pro 23H2 (Build 22631.4169)

### Additional context / 補足

ログファイルも添付しておきます

[vrc-get-2024-10-08_00-18-36.608089.log](https://github.com/user-attachments/files/17285865/vrc-get-2024-10-08_00-18-36.608089.log)
[vrc-get-2024-10-08_00-27-11.813321.log](https://github.com/user-attachments/files/17285866/vrc-get-2024-10-08_00-27-11.813321.log)

**Comment by tai-cha** [comment]
ちなみにVCCのバージョンはv2.3.4です

**Comment by anatawa12** [comment]
VCC.litedbが壊れてる(想定外になっている)かもなのでvcc.litedbを送信していただけますか

**Comment by tai-cha** [comment]
そのままだとUP出来なかったのでZIPで圧縮しました
生ファイルのまま必要であれば別所で上げます🙏🏻 
[vcc.liteDb.zip](https://github.com/user-attachments/files/17285927/vcc.liteDb.zip)

**Comment by tai-cha** [comment]
VCC側で破損したバージョン記述自体は削除できそうだったのでその状態では起動できました
![image](https://github.com/user-attachments/assets/72da6644-3442-48d3-b005-52b69d4e27a2)

**Comment by anatawa12** [comment]
https://github.com/vrc-get/vrc-get/blob/523232daf59a01179c53ef2ad3f679bb2d54780f/vrc-get-vpm/src/environment/unity_management.rs#L229-L231

Option<T>でも`deserialize_with`があるとだめなのか。修正しておきます
