### ISSUE TITLE
バックアップフォルダを含むドライバがマウントされていないとよくわからないエラーでバックアップに失敗する

### ISSUE THREAD

**Issue by mo4ca** [vrc-get/vrc-get#1595]
### Description of the bug / バグの説明

バックアップボタンを押してバックアップを試みると

```
failed to create whole tree
```
とログに出力されてバックアップに失敗する。

### Steps to Reproduce / 再現手順

1. バックアップボタンを押す。

### Expected Behavior / 想定される挙動

バックアップが作成されるべき

### Software Version / バージョン情報

v0.1.15

### OS

Windows11 Pro 23H2 / Windows 10.0.22631

### Webview Version / Webviewバージョン

129.0.2792.79

### Additional context / 補足

裏でUnityHubやUnityEditorが動いたりはしていないようでした。

**Comment by mo4ca** [comment]
ドライブを入れ替えた際にドライブレターが変更されて存在しないパスがバックアップの保存先に設定されていました。お騒がせしました。

**Comment by anatawa12** [comment]
そのような場合もちゃんとしたわかりやすいエラーを出すべきなのでOpenします
