### ISSUE TITLE
defaultProjectPathが`C:`のようになっていると、プロジェクト作成時に"project path must be absolute"エラーになってしまう

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1614]
### Description of the bug / バグの説明

ALCOMでドライブを直接した時は`C:\\`になります。
フォルダそのものを指定されていると捉えれば、末尾に`\\`がつかないことは考えられる?ので、とりあえずいい感じにしておくと良さそうですね。

なお、この状態では、ファイル/フォルダは作成されますが途中でコケる感じみたいです。
どこまで上手くいってるのかは分かっていません。

### Steps to Reproduce / 再現手順

1. settings.jsonを編集
2. プロジェクト新規作成

### Expected Behavior / 想定される挙動

正常動作する

### Software Version / バージョン情報

0.1.16-beta.1

### OS

Windows 10.0.19045

### Webview Version / Webviewバージョン

129.0.2792.89

**Comment by anatawa12** [comment]
https://github.com/vrc-get/vrc-get/blob/09b261ac4e43fdaba4b2562f2c1ea51e74f65a05/vrc-get-gui/src/commands/environment/projects.rs#L642-L643

ここで`C:someProject`になっちゃってるんだと思うので良い感じに修正する必要ありそう
