### ISSUE TITLE
Unityプロジェクト名のフォルダに「.」が複数含まれる場合のバックアップの挙動について

### ISSUE THREAD

**Issue by Saimyozi** [vrc-get/vrc-get#1616]
### Description of the bug / バグの説明

フォルダ名に「.」を複数含むプロジェクトのバックアップを取得する場合
末尾に正常に日付が付与されずにバックアップを取得する度に同名ファイルへの上書きとなってしまう。

### Steps to Reproduce / 再現手順

プロジェクトフォルダ名：Avatar_VCC_2022.3.22f1
実際に取得されたバックアップのファイル名：Avatar_VCC_2022.3.zip　(こちらに毎回上書きされる)

### Expected Behavior / 想定される挙動

フォルダ名全て+日時.zipで都度保存される

### Software Version / バージョン情報

0.1.15

### OS

Windows 11 Pro 23H2

### Webview Version / Webviewバージョン

129.0.2792.89

**Comment by anatawa12** [comment]
拡張子追加処理がバグってるのか。ありがとうございます。
