### ISSUE TITLE
dependenciesになっているパッケージが手元のrepoに無い場合、何が不足しているかよりわかりやすく表示して欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1631]
### Summary / 概要

idだけでも良いのであると良いと思います
(ちなみにvrc-getは出るんでしょうか?)

### Purpose / 目的

利便性向上

**Comment by anatawa12** [comment]
https://github.com/vrc-get/vrc-get/blob/b87b40c82ad64db57c8b3bbf2bba3162e9944c5a/vrc-get-vpm/src/unity_project/package_resolution.rs#L488-L490

このえらーでid自体はトーストには出てくると思う

**Comment by Tliks** [comment]
Sayamameさんに言ったのは自分ですが、確認したら確かにトーストで不足するパッケージのIDは出てました。すみません、記憶違いだったようです。

**Comment by Sayamame-beans** [comment]
とすると、今のところi18n対象になってないだけって感じです?

**Comment by Tliks** [comment]
以下のような形でローカライズはされてませんが、エラーとしては正しく出てます
![Image](https://github.com/user-attachments/assets/b050d734-ae64-499e-859c-0f77bbfb8ba6)

**Comment by anatawa12** [comment]
ローカライズ対象にはちゃんとするべきではある。最近そのための仕組み作ったし。

**Comment by anatawa12** [comment]
- レポジトリを追加すれば治る可能性が高いって話をメッセージに入れたい
- パッケージがあるけどバージョンが見つからなかったというのと、パッケージ自体がないパターンを区別したい

**Comment by Sayamame-beans** [comment]
トーストに詰めるには情報量がつらいかも?

**Comment by anatawa12** [comment]
何かしらちゃんとしたダイアログ出してもいいかもと少し思ってる。

それこそ VPM Catalog のデータの使用許可とかもらって package id から入れられるレポジトリを recommendation してもいいし

**Comment by Sayamame-beans** [comment]
ありかも

**Comment by anatawa12** [comment]
- 現状だと一つでも足りないとそれだけでエラーにするけど、分かる範囲でできる限り不足パッケージを表示したい
