### ISSUE TITLE
vpmDependenciesに指定されたパッケージを追加しようとするときの挙動がVCCと異なる

### ISSUE THREAD

**Issue by eai04191** [vrc-get/vrc-get#1696]
### Description of the bug / バグの説明

`"net.rs64.tex-trans-tool": "0.8.6 || 0.9.0-beta.0"`というvpmDependenciesを持つパッケージ`com.aoyon.auto-configure-texture` `0.2.0`をインストールしようとするとき、VCCでは`net.rs64.tex-trans-tool` `0.8.6`を追加するが、vrc-getは`net.rs64.tex-trans-tool` `0.9.0-beta.0`を追加しようとする

com.aoyon.auto-configure-textureのpackage.json :
https://github.com/Tliks/AutoConfigureTexture/blob/03cb1f4ae5be82b28edde8d85aac225289e392ad/package.json

### Steps to Reproduce / 再現手順

1. https://tliks.github.io/vpm-repos/ をrepoに追加する
2. 空のアバタープロジェクトを作成する
3. `vrc-get install com.aoyon.auto-configure-texture` を実行する
4. net.rs64.tex-trans-tool version 0.9.0-beta.0 がインストールされようとする

```
PS F:\projects\unity\vrc\test-vpm-3> vrc-get install com.aoyon.auto-configure-texture
You're installing the following packages:
- net.rs64.tex-trans-tool version 0.9.0-beta.0
- com.aoyon.auto-configure-texture version 0.2.0
- nadena.dev.ndmf version 1.5.6
You're adding the following packages to dependencies:
- com.aoyon.auto-configure-texture version 0.2.0
Do you want to apply those changes? [y/n]
```

### Expected Behavior / 想定される挙動

- net.rs64.tex-trans-tool version 0.8.6 がインストールされようとする

### Software Version / バージョン情報

1.8.2

### OS

Windows 11 Pro 23H2

### Additional context / 補足

私はvpm-manifestの仕様をちゃんと理解していないため`"0.8.4 || 0.9.0-beta.0"`という指定がどう解釈されるべきなのか（そもそも定義されているのか）をよくわかっていません。
これがinvalidなものなら無視してしまってもいいのかもしれないです

この挙動は最初にALCOMで確認しましたがvrc-get cliでも再現したのでvrc-get cliのbugとしてissueを作成しました

**Comment by anatawa12** [comment]
報告ありがとうございます。

`"0.8.4 || 0.9.0-beta.0"`は `0.8.4` または `0.9.0-beta.0` のいずれかという意味なので、 `0.9.0-beta.0` はバージョン指定に矛盾はしてません。

しかし、VCC/ALCOMでAllow Prerelease Packagesが指定されていない場合にはできる限り Prereleaseパッケケージを入れないほうが正しい動作であるためバグと言えます。

vrc-getでは`1.0.0-beta.0`以降のようなバージョン指定に対応するためにバージョン範囲指定にPrereleaseが使用されてる場合には allow Prerelease Packages (または--prereleasesコマンドライン引数)にかかわらずPrereleaseを含んだ検索をするようになってますが、これをPrereleaseを含まなくても見つかる場合にはそれを優先するようにします

**Comment by anatawa12** [comment]
調べてみたらこの動作はALCOMではすでに治っており、 vrc-get については未リリースなため治ってないようでした。

vrc-get v1.9.0 (ALCOM v1と同時期を予定してます)をお待ちください。

**Comment by eai04191** [comment]
ALCOMではすでに治っているというのは、現在の最新リリースであるALCOM 0.1.16で発生しないという認識であっていますか？
私の環境では0.1.16で発生しているようです

![Image](https://github.com/user-attachments/assets/110a3281-9145-4489-8c9c-d11de0b6aa64)
![Image](https://github.com/user-attachments/assets/fe76ea6e-4999-453e-ad37-07417fd243ff)

**Comment by anatawa12** [comment]
あーごめんなさい。再現しました。実装の見るべき場所を誤っていました。
