### ISSUE TITLE
Wrong License name is shown for parseargs because package.json or LICENSE file lies

### ISSUE THREAD

**Issue by lonelyicer** [vrc-get/vrc-get#1744]
### Description of the bug / バグの説明

![Image](https://github.com/user-attachments/assets/584e63e7-084e-4596-ac69-05ee9cc24c4e)

### Steps to Reproduce / 再現手順

Just open License page

### Expected Behavior / 想定される挙動

Should show `Apache License`

### Software Version / バージョン情報

0.1.16 (57003d4bca2eecbc75bbe6d7fa34d296e9863fd6)

### OS

Windows 10.0.26120 - x86_64

### Webview Version / Webviewバージョン

131.0.2903.86

**Comment by lonelyicer** [comment]
[It looks like it's an upstream problem
https://github.com/pkgjs/parseargs/issues/153

**Comment by anatawa12** [comment]
Actually the package is unused since it's only used by bin part of glob npm package and bin part of glob npm package is completely unused.

I feel it's better for npm to provide some way to omit bin part of package from dependency but not exists......
