### ISSUE TITLE
パッケージ管理の"VPMパッケージ/ユーザーパッケージ"間移動はアニメーション不要かもしれない

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1765]
### Description of the bug / バグの説明

レイアウトが同じなので切り替えた時に点滅するような感じが強く出る気がします。
恐らくアニメーションすべき対象ではないと思います。

### Steps to Reproduce / 再現手順

1. パッケージ管理ページを開く
2. VPMパッケージ/ユーザーパッケージの表示を切り替える

### Expected Behavior / 想定される挙動

アニメーションしない

### Software Version / バージョン情報

0.1.17-beta.0 (71cdcc52644db3f001433a0213e7d46b49419254)

### OS

Windows 10.0.19045 - x86_64

### Webview Version / Webviewバージョン

131.0.2903.99

**Comment by anatawa12** [comment]
上のバーはアニメーションせずに、下側のメインだけけアニメーションすると良い？

**Comment by Sayamame-beans** [comment]
その可能性はあるかも
