### ISSUE TITLE
新しく追加された不足パッケージに関するダイアログのUIで、文章と箇条書きの間は隙間がある方が良いかも

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1768]
### Summary / 概要

文章と箇条書き(パッケージ一覧)の間は隙間がある方が良さそうです。
![Image](https://github.com/user-attachments/assets/53362c1c-f4a4-4c3c-b5ac-c812628a11e6)

### Purpose / 目的

見やすさ向上

### Additional context / 補足

不要だと思ったらcloseしてください

**Comment by anatawa12** [comment]
あって良さそう
