### ISSUE TITLE
[dev] 設定とUI Paletteはどちらを開いていても両方ハイライトされている

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1770]
### Description of the bug / バグの説明

画像参照です

### Steps to Reproduce / 再現手順

当該画面を開く

### Expected Behavior / 想定される挙動

片方のみ

### Screenshots / スクリーンショット

![Image](https://github.com/user-attachments/assets/9e0ac226-89d5-43d1-8306-1ca21b6abf33)

### Software Version / バージョン情報

0.1.17-beta.0 (d7e2505ecf6075c7f2fbbabfe625d2899ccc09a4)

### OS

Windows 10.0.19045 - x86_64

### Webview Version / Webviewバージョン

131.0.2903.99

**Comment by anatawa12** [comment]
基地で、ui palletteを、移動予定
