### ISSUE TITLE
Version conflict check doest not support complex semver

### ISSUE THREAD

**Issue by lackofbindings** [vrc-get/vrc-get#1777]
### Description of the bug / バグの説明

I have a package that uses a semver involving the `||` operator in its vpmDependencies as follows:
```
"vpmDependencies": {
    "sh.orels.shaders": "^6.3.0 || ^7.0.0",
  }
```
In the VCC this is interpreted correctly and the package is allowed to install against ^7.0.0. However in ALCOM the `||` symbol is seemingly not understood and it interprets it as if only the left operand `^6.3.0` exists. 

### Steps to Reproduce / 再現手順

We will be using the following two repos as an example:
- https://orels1.github.io/orels-Unity-Shaders/index.json
- https://lackofbindings.github.io/ORLModules/index.json

1. Starting with any blank project. 
2. Install sh.orels.shaders@7.0.0-dev.3
3. Attempt to install com.lackofbindings.orlmodules@1.7.2

ALCOM will attempt to downgrade sh.orels.shaders to 6.4.0-dev.12.

### Expected Behavior / 想定される挙動

ALCOM should recognize that 7.0.0-dev.3 also satisfies `^6.3.0 || ^7.0.0` and allow the install without attempting to downgrade sh.orels.shaders. 

### Software Version / バージョン情報

0.1.16

### OS

Windows 11 Home

### Webview Version / Webviewバージョン

131.0.2903.99

**Comment by anatawa12** [comment]
There is code to support || pattern so it might e some other issue

**Comment by anatawa12** [comment]
This behavior is expected in vrc-get since accepting this is an bug in `SemanticVersioning` nuget package, which is used by VCC.

I'm considering if this should be supported for now, but I don't like implement bug

**Comment by anatawa12** [comment]
I forgot to describe what's the bug.

`^7.0.0` means `7.0.0` or later but not `8.x.x` series so it should mean `v >= 7.0.0` and `v < 8.0.0-0`.

However, old SemanticVersioning package was think as `v >= 7.0.0-0` and `v < 8.0.0-0`, which falsely accepts beta releases of 7.0.0, which is older than `7.0.0`.

**Comment by lackofbindings** [comment]
Ah ok so it’s mostly just a mistake on my part then. What should the config look like to get my desired behavior in both the VCC and ALCOM?

Should it be `^6.3.0 || ^7.0.0-0` ?

**Comment by anatawa12** [comment]
> Should it be `^6.3.0 || ^7.0.0-0` ?

Yes or possibly `^6.3.0 || ^7.0.0-dev.1` for cleaner description.
(to understand `-0` may require knowlage that `0` is the smallest prerelease version, but `-dev.1` is does not require I think.)

**Comment by lackofbindings** [comment]
Thanks for your help, I'll close this as mostly being my fault for not fully understanding semver & the VCC being slightly buggy.
