### ISSUE TITLE
ウィンドウの幅が狭い場合、Unityを開くボタンは右側にあって欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#1778]
### Description of the bug / バグの説明

画像参照
ウィンドウの幅が足りない場合、Unityを開くボタンが左側に来てしまいます

### Steps to Reproduce / 再現手順

1. プロジェクト管理画面を開く
2. ウィンドウの幅を縮める

### Expected Behavior / 想定される挙動

Unityを開くボタンは右側にある

### Screenshots / スクリーンショット

![Image](https://github.com/user-attachments/assets/11ef29ee-0955-4245-a142-46a2420d1bdd)

### Software Version / バージョン情報

0.1.17-beta.1 (81938cec03ecaa5566a57216e73a279e87ca45f3)

### OS

Windows 10.0.19045 - x86_64

### Webview Version / Webviewバージョン

131.0.2903.99

**Comment by anatawa12** [comment]
分けてみたら一応それっぽくなったかな。少し実装変更予定あり
