### ISSUE TITLE
Unity Hub redirect on Unity website in Japan when using English language

### ISSUE THREAD

**Issue by tismatis** [vrc-get/vrc-get#1809]
### Description of the bug / バグの説明

When you set your language to English at the setup of ALCOM and you don't have Unity Editor of installed, you will want to download Unity Hub from the website of Unity using the given button but that open the Japan Website of Unity on download.

### Steps to Reproduce / 再現手順

1. Install ALCOM on a system that doesn't had Unity Hub
2. Start the setup and set to english or any language except japan
3. Click on "Download Unity Hub from unity.com"

### Expected Behavior / 想定される挙動

That open the website of Unity in the selected language or at least in english.

### Software Version / バージョン情報

0.1.17

### OS

Windows 11 LTSC 24H2

**Comment by anatawa12** [comment]
I completely forgot it's hard-coded to JA. thank you

**Comment by tismatis** [comment]
No problem ^^'
I was fixing it on my side but you pushed it before I got the time to commit on my fork xD
