### ISSUE TITLE
vcc:のハンドリング

### ISSUE THREAD

**Issue by anatawa12** [vrc-get/vrc-get#391]
- macOSでは常にやっていいと思う
- windowsはVCCが入ってなかったらやって、入ってたら上書きするか聞く？

`vcc://vpm/addRepo`

**Comment by anatawa12** [comment]
https://github.com/tauri-apps/tauri/issues/323
https://github.com/tauri-apps/tauri/pull/8680

**Comment by anatawa12** [comment]
linuxってどうすればいいんやろね

**Comment by KisaragiEffective** [comment]
> linuxってどうすればいいんやろね

~/.local/share/applicationsにdesktop entry (Windowsで言うショートカット) をおいてxdg-open(1)などで紐づけるとうまくいきます

**Comment by anatawa12** [comment]
tauri v2が必要そうなので一旦milestoneから外す

**Comment by anatawa12** [comment]
[`class_addMethod`](https://developer.apple.com/documentation/objectivec/1418901-class_addmethod) でどうにかなった。

**Comment by anatawa12** [comment]
linuxもインストールに近い処理が一回必要そうなので、仕組みだけ用意してインストール機能は #593 でやることにします。

**Comment by anatawa12** [comment]
windowsの参考: https://learn.microsoft.com/ja-jp/windows/win32/wmp/custom-scheme-registry-settings
