### ISSUE TITLE
vrc-get-guiの正式名称を募集しています

### ISSUE THREAD

**Issue by anatawa12** [vrc-get/vrc-get#453]
今のところtauriのロゴが割り当てられてるけど変えないといけない

**Comment by anatawa12** [comment]
https://misskey.niri.la/notes/9qd8y37fkw

**Comment by anatawa12** [comment]
vrc-get-guiから変えようと最初にしてた理由の一つである"vrc"という単語については [このtupperさんの回答](https://ask.vrchat.com/t/branding-guideline-for-tool-or-service-names/22313/4) で解決しちゃってるから変える必要ないんじゃないかという話もある

**Comment by anatawa12** [comment]
al(ternativr creator )com(panion) => alcom アルコム (by @Sayamame-beans )

**Comment by Spokeek** [comment]
Open Creator Companion (OCC)
Optionally, maybe Open VRChat Creator Companion (OVCC), to reuse the VRChat keyword name, as mentionned in tupper's post.

**Comment by anatawa12** [comment]
Thank you for suggestion. however, I don't like to use something repeats 'CC' in short because it will confuse users with official VCC.

**Comment by Sayamame-beans** [comment]
(I think this should be true especially for non-developer Japanese users who are not familiar with English-based Softwares.)

**Comment by Spokeek** [comment]
Need something with more ... personality then. But i'm bad in marketing
