### ISSUE TITLE
Add the "Add command line augments" button to the in Open Unity button option.

### ISSUE THREAD

**Issue by YTJVDCM** [vrc-get/vrc-get#454]
時にコマンドライン引数が必要になる場合があるため、vrc-get-guiにもUnity Hubにおける"Add command line augments"([Unity Editorのコマンドライン引数](https://docs.unity3d.com/Manual/EditorCommandLineArguments.html)を設定する機能)に該当するボタン・機能の実装

**Comment by anatawa12** [comment]
これってプロジェクトごとの方が良いですかね

**Comment by YTJVDCM** [comment]
Unityバージョンによって使用可能な引数や使い方が変わったり、そもそもプロジェクトによって使い分けたいという気持ちがあるのと、本家Unity Hubに合わせるという意味でも、プロジェクト毎に設定できる方が望ましいと思われます。

一応私としては各プロジェクトのManage画面右上に同項目が追加される形を想定していました。
![Screenshot_20240314_043616](https://github.com/vrc-get/vrc-get/assets/50657624/35df35d4-b829-4d1f-9974-31c558411bd5)
