### ISSUE TITLE
[vrc-get-gui] ウィンドウサイズを保存する

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#458]
現状保存されていないようなので一応…
(いずれするつもりではあるかな?と思ってはいますが)

**Comment by anatawa12** [comment]
あんまり考えてなかった

https://github.com/tauri-apps/tauri/discussions/2954

**Comment by anatawa12** [comment]
参考: https://github.com/tauri-apps/plugins-workspace/blob/ed682dd96eb765e7cd3cdbc3cc64f794a0d6f9df/plugins/window-state/src/lib.rs#L127-L226

これだとapp config dir以下になってるけどvrc-getのコンフィグの中にしたいかなぁ
