### ISSUE TITLE
[vrc-get-gui] VCCに比べて文字が少し大きいため、必要なウィンドウ幅が大きすぎる?

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#459]
![image](https://github.com/anatawa12/vrc-get/assets/61457993/08270fe4-bdea-461a-8ae9-4d2e28f73b55)

VCCも、表示が小さくなれば端が切れてスクロールが必要になりますが、以下のような挙動になっているようです。
ちょっと足りなくなる→Project Nameカラムを縮める
Project Nameカラムをそれ以上縮めたくない幅まで縮めた→スクロールが必要になる

vrc-get-guiは、現状ボタン数もVCCより多いので、幅と文字の大きさについてはちょっと検討の余地がありそうです。
(見切れると、どうしても初見では範囲外の要素は存在しないものとして認識されやすいので)

それをした次に検討する面倒なアイデアの1つとしては、カラムの幅を手動で調整可能にするのも需要があるかもしれません。

**Comment by anatawa12** [comment]
プロジェクト名部分の幅が大きすぎるとは思ったのですが、デフォルト状態において上限を付ける方法がわからなかったんですよね... cssに負けた

**Comment by kurotu** [comment]
#597 を起票しましたが、おそらくこちらこそが解決すべき問題な気がします。
案出し程度のものですが、こちらにも転記しておきます。

----

- Name列を完全に自動幅にしてしまい、横スクロールの必要な状況が発生しないようにする。
    - Name列が狭くなることは許容する。
    - 一定以上狭ければ、領域を稼ぐために左端メニューをアイコンだけにしてもよいかも。
- ウィンドウが一定の幅以下になったらテーブルをやめて専用レイアウトにする。(レスポンシブ化)
    - VCCはGrid Viewに切り替えればウィンドウ幅が狭い場合の対応ができます(できてない)。

![image](https://github.com/vrc-get/vrc-get/assets/74851548/0c4a78f0-ff77-4424-bfac-c1dac795e1f2)
