### ISSUE TITLE
成功トースト通知のタイマーがvrc-get-guiのウィンドウがアクティブでないときにも進むようにする

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#529]
### Description of the bug / バグの説明

トースト通知の時間経過がバックグラウンドで機能しません。
info相当の内容(Unity起動など)はバックグラウンドで時間経過させてしまって良い気がします。
ただ、その内容がエラー/警告相当である場合、非アクティブな間は動かず残っておいた方が良い気もするため、何とも言い難いです。

### Steps to Reproduce / 再現手順

1. プロジェクトを開く
2. vrc-get-guiのウィンドウを非アクティブにする(ブラウザを見る等?)

### Expected Behavior / 想定される挙動

トースト通知の時間経過はバックグラウンドでも発生するはず

### Software Version / バージョン情報

0.1.0-beta.4

### OS

Windows 10 Pro 22H2

### Additional context / 補足

面倒だったらwon't fixして良いと思います。多分支障はあまりないと思うので…

**Comment by anatawa12** [comment]
toast毎に設定いじれるようなのでunity起動等は確かに秒数フォーカスなくても進んで良さそう
