### ISSUE TITLE
vrc-get-gui自身の自動更新機能

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#531]
### Summary / 概要

タイトル通りです。
vrc-get-guiの終了時に更新する(VSCodeみたいな方式)とか、手動更新(アップデートボタンを表示する(VCCみたいな)方式)あたりの組み合わせになりそうです。
前者だけだと、開きっぱなしのケースに対応出来ないので、更新を見つけたら誘導する必要があると考えました。
後者についても、数日経ったら/複数ウィンドウ起動したらダイアログ出すみたいなことしても良いかもしれません…? (気付きやすい様に。ただボタンがあるだけだと気付いて貰えないことはVCCが証明していると思います。)

### Purpose / 目的

古い状態で使い続けられることを防止します。

**Comment by anatawa12** [comment]
related document:
