### ISSUE TITLE
Popup message while opening Unity

### ISSUE THREAD

**Issue by lu-na-r** [vrc-get/vrc-get#532]
### Description of the bug / バグの説明

The popup message while vrc-get-gui is opening Unity should be "Opening Unity..." rather than "Unity is opening...".

### Steps to Reproduce / 再現手順

Press the "OPEN UNITY" button.

### Expected Behavior / 想定される挙動

The message should be "Opening Unity..."

### Software Version / バージョン情報

0.1.0-beta.4

### OS

macOS 14.2.1

**Comment by anatawa12** [comment]
気づいててi18n時にまとめて色々治す予定です

**Comment by lu-na-r** [comment]
Got it. Thank you.
