### ISSUE TITLE
uesr packageの管理機能

### ISSUE THREAD

**Issue by anatawa12** [vrc-get/vrc-get#553]
### Summary / 概要

uesr packageの管理機能

### Purpose / 目的

ないと稀に困るかもしれない

### Additional context / 補足

vrc-get cliにもない

**Comment by anatawa12** [comment]
Settingsの中にいれるか新たに右についかするか悩んでる。追加先の意見募集中です

**Comment by anatawa12** [comment]
I think it might also be good to have local packages in different tab in vpm repositories page (it should be renamed).

**Comment by Sayamame-beans** [comment]
localのVPMPackageだけでなく、unitypackageを登録出来ると操作がALCOM上で完結して楽かもしれない?(参考: [VRCUnity勉強会より](https://discord.com/channels/737454833258201198/737472691514114080/1255669356722000023))

import時に他ツールが特別な処理をする可能性が無ければ、予め展開したものをVPMパッケージのように配置すると良いのかも

懸念点: remove方法
importのみ可能でも良いかも。

**Comment by anatawa12** [comment]
unitypackageは完全に別issue生やしてほしい
