### ISSUE TITLE
リポジトリを選択していない状態で、そのリポジトリのパッケージを見た時の表示を改善

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#558]
### Summary / 概要

現状は、バージョンが空で、LatestとSourceがnoneになっています。
repoの中身見るのも、現在のバージョンをlatest扱いにする(VCCの挙動)のも、どちらの挙動も変なので、本来と同じような表示はしなくて良いと思っていますし、バージョン一覧に何も表示されないのもそれはそれで良いかなと思っています。
ただ、少し分かりづらさはあると思うので、何か分かりやすくする術は無いでしょうか…?
(確か、複数repoから載っている場合は`Multiple Sources`と表示するようになっていましたね…? 同じような感じで何とかならないでしょうか?)

![image](https://github.com/vrc-get/vrc-get/assets/61457993/252f3122-2166-4cc9-8ae0-7421893e5847)

### Purpose / 目的

リポジトリが選択されていないために表示されていないということが分かりやすいようにする。

**Comment by anatawa12** [comment]
Latestはselected repositoriesからみてるのでnoneが正しいのでそっちはそのままにします。

Repositoriesのところに`Not Selected`てきな表示をgrayでいれるのがいい感じ・

**Comment by Sayamame-beans** [comment]
何となく良さそうな気がします?

**Comment by anatawa12** [comment]
<img width="1210" alt="image" src="https://github.com/vrc-get/vrc-get/assets/22656849/79755a63-701a-4ced-993c-550d0f2311bb">
