### ISSUE TITLE
初回セットアップの仕組み

### ISSUE THREAD

**Issue by anatawa12** [vrc-get/vrc-get#593]
#308 とか #268 の追加や #391 とかであるべき

search terms: setup initial

初回セットアップでやるべきこと
- Locale Settings
- Color Theme
- install unity hub if not exists
- install unity if not exists
- backup format
- default project / backup 場所の更新
  - if VCC is not configured yet, I think it's better to save at `Documents/VRChatProjects` and `Documents/VRChatBackups`
- ask for installing `vcc:` handler 

Related
- #308
- #268
- #391
- #612

**Comment by Sayamame-beans** [comment]
(他にはUnity Hubの導入誘導やUnityの導入などがある)

**Comment by Sayamame-beans** [comment]
初回導入時、OSの言語が日本語だったら日本語表記を初めにしても良い気が少ししたり?

**Comment by anatawa12** [comment]
> 初回導入時、OSの言語が日本語だったら日本語表記を初めにしても良い気が少ししたり?

はやった

**Comment by anatawa12** [comment]
might be used: https://github.com/shadcn-ui/ui/pull/318

**Comment by anatawa12** [comment]
Decide which part should be checked and not

- Language setting
- Other appearance setting
  - This includes color theme but other might need add in the future
- Install Unity Hub
- Project Location
  - Huge warning if default path is under LocalAppData (not backuped) or non ASCII path (may cause CE)
- Backup Settings
  - Format and Location
- vcc:// instillation
- Other System Settings
  - Hostname

(7 steps)

We have to think

- Should we suggest installing Unity after installing Unity Hub?
  - Should we suggest if Unity Hub is already installed but Unity isn't?
    - Checking if unity insulation is enabled took few seconds so how should we suggest?

**Comment by anatawa12** [comment]
I think setup pages should not have side bar. We might create [Route Groups](https://nextjs.org/docs/app/building-your-application/routing/route-groups) for existing page for current UI with sidebar and another group and path for setup pages
