### ISSUE TITLE
デフォルトのウィンドウサイズの幅を広げる

### ISSUE THREAD

**Issue by kurotu** [vrc-get/vrc-get#597]
### Summary / 概要

表題のとおり、起動時のウィンドウサイズの幅を広くしてほしいです。
#458 が実装されるまでのつなぎ的なものでかまいません。

### Purpose / 目的

起動時の状態で「Open Unity」「Manage」「Backup」の各ボタンが隠れてしまっており、毎回リサイズまたは横スクロールの手間が生じているので解消したいです。

![image](https://github.com/vrc-get/vrc-get/assets/74851548/c3896b62-1e1c-4ac5-b43f-c34592c8954d)

好んでウィンドウを小さく設定する分にはよいですが、初見の際はすべて見えていた方が混乱しないかと思います。

### Additional context / 補足

vrc-get-gui v0.1.0-beta.13

**Comment by anatawa12** [comment]
#458 が実装されたので一旦closeしてもいいですかね

**Comment by kurotu** [comment]
Closeで大丈夫です！
