### ISSUE TITLE
material tailwindやめたい

### ISSUE THREAD

**Issue by anatawa12** [vrc-get/vrc-get#601]
色等の設定が分散して面倒。css variable使ったなんかいいのないかな

**Comment by Spokeek** [comment]
So i know about this as some fixes in other issues are linked to tailwind classes. Is removing tailwind a decision that is confirmed or to be discussed ?

**Comment by anatawa12** [comment]
This is not a decision since I didn't tired other ui frameworks I don't know if current problems are going to be fixed with removing tailwind or not.

**Comment by Spokeek** [comment]
I'd say probably won't make them disappear. As this is still a beta id say let's fix the issues there is up to now, and if tailwind pulls us back, then we can always remove it and compare before and after. I'll consider this issue as in discussion if we find something as alternative, tailwind do be quite heavy and provides a lot you may not need.

**Comment by orels1** [comment]
Fwiw tailwind is pretty easy to override colors with CSS variables in, if you want more than just dark/light themes: https://tailwindcss.com/docs/customizing-colors#using-css-variables

Outside of that, tailwind is generally more lightweight than a lot of other CSS frameworks as it strips any utilities that are unused from the final css output

**Comment by anatawa12** [comment]
After a few research, I found that the actual problem is from the theme system in material tailwind, not the tailwind itself so I think it's not good to leave tailwind.

**Comment by anatawa12** [comment]
shadcnが進められた

**Comment by Spokeek** [comment]
> shadcnが進められた

I really like that design used by github, love the idea

**Comment by anatawa12** [comment]
Fixed in #1028
