### ISSUE TITLE
project typeのアイコンは表記の内容に依存しており、localizeで壊れる

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#617]
### Description of the bug / バグの説明

~~"Words"になってしまっています。~~ fixed by #625 
また、アイコンが?なのも気になります ~~(元々こうでしたか?)~~

### Steps to Reproduce / 再現手順

~~ワールドプロジェクトが一覧にあれば再現します~~
新しい言語ファイルを用意するか、en.json5の中身を書き換えて表示内容を変更することで、任意のプロジェクトで再現可能です

### Expected Behavior / 想定される挙動

ワールド/アバターに対応する適切なアイコンが表示される

### Screenshots / スクリーンショット

![image](https://github.com/vrc-get/vrc-get/assets/61457993/b43d593c-fe57-4aa4-923a-0828b0ba5fb8)

### Software Version / バージョン情報

0.1.0-beta.15

### OS

Windows 10 Pro 22H2

**Comment by Sayamame-beans** [comment]
アイコンがおかしい理由が分かりました。
表示内容の"Worlds", "Avatars"の文字列一致で判定していますか?
日本語翻訳のテストで"ワールド", "アバター"を入れるとアイコンが?になってしまいました。

**Comment by Sayamame-beans** [comment]
Closed by #625

**Comment by Sayamame-beans** [comment]
そんなことなかった(アイコン問題)

**Comment by anatawa12** [comment]
翻訳かける前を変数に入れてそれで判定すればいいのでgood firstにします
