### ISSUE TITLE
プロジェクトを開くUnityバージョンの選択

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#626]
### Summary / 概要

2019.4.29f1から2019.4.31f1にしたり、2022.3.6f1から更新された場合等に使用?

### Purpose / 目的

VCCにはある

### Additional context / 補足

選択欄はあるが、空っぽ
![image](https://github.com/vrc-get/vrc-get/assets/61457993/330a1486-9a45-4c59-8613-8afe2b8dde26)

**Comment by Sayamame-beans** [comment]
VCCでは最新の推奨バージョン以外はあまり想定していなさそうな雰囲気(変更や移行操作自体は出来そうですが)
想定されるバージョン2つ以外はチェックを入れないと表示されない形式
![image](https://github.com/vrc-get/vrc-get/assets/61457993/f6722e67-03df-4999-a0ef-562281086573)

**Comment by Sayamame-beans** [comment]
今考えていること
- 選択ダイアログを表示する形にする
  - 非対応バージョンはVCCみたいに畳んで隠す?
  - 非推奨バージョンは、非対応バージョンといっしょに混ぜてしまうのではなくて、区別して載せておいても良さそうな感じ。(2022.3.22f1になったとして、2022.3.6f1が対応バージョンではあるということを分かるようにしておきたい)
  - 上の方に現在のバージョンを書いておくと非対応バージョン等になっているときでも分かりやすくて良さそう
- 旧推奨バージョンは最低でもメジャー単位では保持しておきたい感じがある(2019なら4.31f1)
- 一番推奨されているバージョンにVCCみたいに印を載せるかは悩みどころ
- 下げる方向のmigrateは非推奨。警告を出したい。
  - Majorなら言わずもがな、Minorでもアップロード済みのものは更新が適用されなくなるはずなのでその旨を警告?

**Comment by anatawa12** [comment]
Recommendedへ変える機能だけ #842 として実装して一旦後回しにする
