### ISSUE TITLE
開発時のホットリロードで言語設定をロールバックしないで欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#636]
### Summary / 概要

現在、日本語翻訳を用意しているのですが、ファイルを更新してホットリロードが入ると、(設定値は日本語のままですが)英語で表示されてしまいます。
この状態で、ページ全体のリロードを行う(左側のProjectsやRepositoriesなどを押す)と、日本語に戻ります。
リロード時に英語に戻らないようになると嬉しいです。

### Purpose / 目的

開発しやすくなる

**Comment by JustBuddy** [comment]
Pressing CTRL+R on your keyboard after the hot reload will also switch it back to the selected language, a workaround for now.

**Comment by Spokeek** [comment]
Isn't this fixed by https://github.com/vrc-get/vrc-get/pull/1057 ?

**Comment by anatawa12** [comment]
If we moved to another page, language settings might be roll-backed.
