### ISSUE TITLE
パッケージ管理画面のパッケージ表示順が固定でない

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#640]
### Description of the bug / バグの説明

タイトル通りです。
表示する度に順番が変化するようです。

### Steps to Reproduce / 再現手順

分かりやすい再現手順: Reflesh Packagesを何度も押す

### Expected Behavior / 想定される挙動

表示順が一貫している

### Software Version / バージョン情報

0.1.0-beta.15

### OS

Windows 10 Pro 22H2

**Comment by anatawa12** [comment]
レポジトリ単位の中で順番が不定になってそう

**Comment by Sayamame-beans** [comment]
こちら、repo一覧で選択してない場合は未選択になるから順番が変わるのは仕様で良いですよね? (確かrepo順表示にすると言っていたと思うので)
