### ISSUE TITLE
RepositoriesのImport/Exportが欲しい

### ISSUE THREAD

**Issue by meronmks** [vrc-get/vrc-get#643]
### Summary / 概要

ほぼ表題の通りでCommunity RepositoriesのImportおよびExportができるとバックアップ等に便利だなと思ったので。

### Purpose / 目的

追加したRepositoriesのバックアップ。
ユーザがオススメのRepositories一覧配布なんて使い方もできるかも。

### Additional context / 補足

RepositoriesをImportするときの画面、どう表示するとかでちょっと面倒そうな気配はする。

**Comment by anatawa12** [comment]
headersもどうしよう

**Comment by anatawa12** [comment]
headersは認証用なので非対応でいいかも

**Comment by anatawa12** [comment]
インポート時、全レポジトリをまとめて表示すればいい？

**Comment by meronmks** [comment]
> インポート時、全レポジトリをまとめて表示すればいい？

そうかも、いっぱいあるとUI的にぎちぎちになったりで大変そうだけど

**Comment by JustBuddy** [comment]
@anatawa12 the current implementation doesn't seem to handle headers at all, even though the dialogues suggests that.
What is the plan for those? I know creators who use headers for authentication, I am getting their opinion on the topic right now.

**Comment by anatawa12** [comment]
We can add repository with headers by using `vcc://vpm/addRepo?url=<url>&headers[]=header` line repository list file.

**Comment by JustBuddy** [comment]
Disregard my previous message, for some reason the repositories I use with headers lost that information at some point.
Headers are exported correctly.
