### ISSUE TITLE
localizationのキーが割り当てられていない文章が所々ある

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#648]
### Description of the bug / バグの説明

タイトル通り
Project removed successfully
Project created successfully
Apply Changes
については気付いたので日本語翻訳とともに修正中です。

### Steps to Reproduce / 再現手順

N/A

### Expected Behavior / 想定される挙動

翻訳可能

### Software Version / バージョン情報

0.1.0-beta.15

### OS

Windows 10 Pro 22H2

### Additional context / 補足

キー`clock <l>here</l> to view licenses of the projects used in vrc-get-gui`はclickの誤字なので、同様に修正中です

**Comment by Sayamame-beans** [comment]
"Licenses"にも付いていないようですね(迷う)
open unityは片方抜けてたので、こっちは今直します

**Comment by Sayamame-beans** [comment]
migrate projectはキーはあるけどenに入ってなかったみたいです(入れます)

**Comment by Sayamame-beans** [comment]
他に見つけた場合はご報告お願いいたします。(平常時に表示されていないどこかにまだありそうな気がする)

**Comment by Sayamame-beans** [comment]
2つ、抜けを見つけました。
https://github.com/vrc-get/vrc-get/blob/dffe524ee0e75a9ad8b7eb413ffe958be569307b/vrc-get-gui/app/projects/manage/page.tsx#L438
https://github.com/vrc-get/vrc-get/blob/dffe524ee0e75a9ad8b7eb413ffe958be569307b/vrc-get-gui/app/projects/page.tsx#L471

**Comment by Sayamame-beans** [comment]
時間の単位が抜けている

**Comment by anatawa12** [comment]
Tooltipに関してはそれなりにありそう。とりあえず `/content=(["']|\{['"])/`でtooltipは調査してまとめて処理します
