### ISSUE TITLE
add addになっている

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#649]
https://github.com/vrc-get/vrc-get/blob/7894539326d0b21fbe92db7d98b8933ad51cf542/vrc-get-gui/lib/open-unity.ts#L12

**Comment by Sayamame-beans** [comment]
ちなみに、unityが1つも無かったら"NoUnityVersionForTheProject"で、あるけど対応したものがない場合が"NoMatchingUnityFound"ですかね?
(分ける必要はあるのでしょうか?)

**Comment by anatawa12** [comment]
NoUnityVersionForTheProjectはプロジェクトが不正でUnityバージョンが未定義の場合ですね

**Comment by Sayamame-beans** [comment]
あ～～
なるほど。
