### ISSUE TITLE
新規プロジェクト保存場所の選択でボタンを押すとズレる

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#668]
### Description of the bug / バグの説明

画像参照
言語設定に依存しません

### Steps to Reproduce / 再現手順

1. プロジェクト作成画面を開く
2. 保存場所を変えようとしてボタンを押す
3. ズレる

### Expected Behavior / 想定される挙動

ズレない

### Screenshots / スクリーンショット

クリックするとこうなります
![image](https://github.com/vrc-get/vrc-get/assets/61457993/9784ccc2-df80-4ca3-bdb9-3518774b45b8)

### Software Version / バージョン情報

0.1.0-beta.15

### OS

Windows 10 Pro 22H2

**Comment by anatawa12** [comment]
Known, 修正方法がわからんのでhelp wanted 状態
