### ISSUE TITLE
新規プロジェクトの保存先選択ウィンドウを開いたままvrc-get-guiを操作出来てしまう

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#669]
### Description of the bug / バグの説明

新規プロジェクトの保存先選択ウィンドウを表示し、それを閉じないままvrc-get-guiを操作することが出来ます。
これにより、作成をキャンセルすることも出来ますが、保存先選択ウィンドウは開いたままになり、再度新規プロジェクトを作成しようとすると、保存先選択ウィンドウが閉じるまで無限ロードします。(キャンセルで画面を戻ることは可能)
("作成する"を押すとエラーが発生し、操作不能になります。
```
TypeError: Cannot use 'in' operator to search for 'Unrecoverable' in invalid args `template` for command `environment_create_project`: command environment_create_project missing required key template
```
)

### Steps to Reproduce / 再現手順

1. 新規プロジェクト作成画面を開く
2. 保存先選択ウィンドウを出す
3. 閉じずにvrc-get-guiに戻る

### Expected Behavior / 想定される挙動

保存先選択ウィンドウがあるときは操作出来ない

### Software Version / バージョン情報

0.1.0-beta.15

### OS

Windows 10 Pro 22H2

**Comment by anatawa12** [comment]
windows specificの動作やめて(泣)
それはそれとして出てくるエラーは別途バグだね

**Comment by Sayamame-beans** [comment]
> windows specificの動作やめて(泣)

win向けソフトだと、選択ウィンドウ表示中は操作不可で、操作しようとするとウィンドウのふちが点滅する+音が鳴るやつがありがちですが、あれってWin側の標準機能的なアレじゃなかったんですね…(或いはrustではそれが用意されてなくて面倒…?)

**Comment by anatawa12** [comment]
少なくともtauriのapiにそれっぽいのはなかったです

**Comment by Sayamame-beans** [comment]
となると、多分vrc-get-guiがアクティブにされた時に選択ウィンドウをアクティブにするのも難しいですよね…?(念の為確認)

**Comment by anatawa12** [comment]
yes

**Comment by Sayamame-beans** [comment]
この辺り、tauri v2になることで出来るようになってたりします? (docsを眺めています)

**Comment by anatawa12** [comment]
よーくAPIみたらv1でもできたっぽい

v2のタイミングで一緒に入れた

**Comment by Sayamame-beans** [comment]
やった〜
