### ISSUE TITLE
他のソフトが開いていることでプロジェクトの削除に失敗しても、その旨は通知されない

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#682]
### Description of the bug / バグの説明

他のソフトが開いていて削除に失敗した場合、通常通り削除されたようなログになりますが、実際には削除されていません。
```
[ Info] vrc_get_gui::commands: removed project directory: E:\VRC_Data\VCC_Projects\unity test
[ Info] vrc_get_gui::commands: removing project directory: E:\VRC_Data\VCC_Projects\unity test
```
ref: https://misskey.niri.la/notes/9rg4a3gr18

### Steps to Reproduce / 再現手順

1. プロジェクト内のファイルをnotepadとかで開く
2. プロジェクトのフォルダをvrc-get-guiから削除する

### Expected Behavior / 想定される挙動

他のソフトが開いていることにより削除出来ない旨が通知される
この際、単にトースト通知を出すのではなく、ダイアログにして再試行可能にしても良いかもしれませんね。

### Software Version / バージョン情報

0.1.0-beta.15

### OS

Windows 10 Pro 22H2

**Comment by anatawa12** [comment]
なんでかというのを出すのは少しむずかしそうなのですが、とりあえず削除にエラーがあったことは表記できそうなのでそれで一旦bugとしてはcloseします

**Comment by anatawa12** [comment]
とりあえずエラーは出るようになった。 #1368
