### ISSUE TITLE
ウィンドウ左下のバージョン番号欄をクリックすることでクリップボードにコピーする機能

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#702]
### Summary / 概要

既にクリック出来るようになっているみたいなので、せっかくならクリックした時にコピー出来ると良いなと思いました。
例えばDiscordで、ウィンドウ左下から自身のプロフィールを表示してユーザーIDのところをクリックすると"コピーされました！"と出てコピー出来るみたいな…他にも何かのソフトウェアで見た記憶があります。

### Purpose / 目的

あると報告時とかに便利そうだと思いました。
(気付かないと使えませんが、この手の地味に便利な機能は時々実装されているのを見かける気がします。Misskeyみたいにクリップボードのアイコン付けるのも、明示的になって良いのかもしれませんね)

**Comment by lu-na-r** [comment]
あったらいいなと思っていました。ぜひ実装していただきたいです

**Comment by anatawa12** [comment]
<img width="1059" alt="image" src="https://github.com/vrc-get/vrc-get/assets/22656849/039bb25d-4568-415b-aa94-2826fe7b0e1f">

これ(最初一分わからなかったのでスクショ添付)

onclickでclipboardに貼り付けてtoast出すだけだと思うのでgood firstにしときます

https://github.com/vrc-get/vrc-get/blob/d3ab402deaf17355d171ffaf69e59a400507354e/vrc-get-gui/components/SideBar.tsx#L37
