### ISSUE TITLE
[style] 設定ページ内で、説明文と題目がほぼ同じ表示で見づらさを感じるので差を付けて欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#716]
### Summary / 概要

タイトル通りです。現在のPR #714 で内容が増えてより強く感じる気がします。
(大きさ等に差が無いので題目と説明という分かれ方に見えない?)
![image](https://github.com/vrc-get/vrc-get/assets/61457993/31153b0c-dbdb-49d0-924b-e61108c1a804)
![image](https://github.com/vrc-get/vrc-get/assets/61457993/03a1c978-0ab7-42f2-b432-8c76a9d15674)

### Purpose / 目的

見やすくなる

**Comment by anatawa12** [comment]
あれ？ここもウェイトの差があるはずなんだけど...
<img width="680" alt="image" src="https://github.com/vrc-get/vrc-get/assets/22656849/ed155f7b-3f70-4777-9700-40a6fbe23c65">

**Comment by Sayamame-beans** [comment]
うぇ…
しばらく前から差が付いてなかったような気がする? (i18n実装する前には付いてたのかもしれませんが記憶していない)

**Comment by Spokeek** [comment]
I could get my hands into this. I would see if I can harmonize the settings page as a whole so each section uses the same design and so we avoid inconsistencies.

**Comment by Spokeek** [comment]
The original issue comes from tailwind that disables all browser specific design values to only give power to css classes that you apply to components.

So here i can re enable the sizing values in the css globals.
By also adding additional margins so the sections are clearer, would give something like this 

![image](https://github.com/vrc-get/vrc-get/assets/4519853/7386e119-5beb-4cd3-930c-d7394e828fc2)

Tell me if that's a good idea or if i should remove all header values and use the classes instead.

**Comment by anatawa12** [comment]
> Tell me if that's a good idea or if i should remove all header values and use the classes instead.

 I think it's ok to use  css globals.
