### ISSUE TITLE
設定ページからバージョンアップ可能にしてほしい

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#733]
### Summary / 概要

今は起動時のダイアログでしか更新出来ないようです。
ダイアログを閉じてしまうと、vrc-get-guiを再起動しないと確認することが出来ません。(更新内容含む)

### Purpose / 目的

一応あった方が良い気がします
なお、VCCでは設定画面にCheck for Updatesボタンがあります

**Comment by anatawa12** [comment]
参考 https://tauri.app/v1/guides/features/menu/
