### ISSUE TITLE
インストール時の指定に依らず、更新時にstart menu folderとデスクトップショートカットが(毎回)作成されてしまう

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#734]
### Description of the bug / バグの説明

タイトル通りです。
更新時にはstart menu folderとデスクトップショートカットの追加処理を行う必要はありません。
(置き換え/編集が必要な場合は、存在する場合にのみ実行するべきです)

### Steps to Reproduce / 再現手順

1. start menu folderのショートカットを作成せずに古いバージョンをインストール
2. デスクトップショートカットも作成しないようにする
3. 起動し、更新する
4. 両方生える

### Expected Behavior / 想定される挙動

生えない

### Software Version / バージョン情報

0.1.0-beta.18

### OS

Windows 10 Enterprise 2004 (Windows Sandbox)

**Comment by anatawa12** [comment]
多分tauri側

**Comment by anatawa12** [comment]
#1350 で治るかも

**Comment by anatawa12** [comment]
多分治ってそう (0.1.14 betaから0.1.14の更新で確認)

0.1.14 => 0.1.15で多分再度確認できるかな

**Comment by anatawa12** [comment]
@Sayamame-beans 治ってますか

**Comment by Sayamame-beans** [comment]
0.1.14からで確認しましたが、デスクトップショートカットは生えなくなってますね
start menu folderは設定項目が無くなってる…?

**Comment by anatawa12** [comment]
多分フォルダが作られなくなってる。

そして(おそらく一般の)インストーラに習ってStart menu にシンプルに追加されてる

**Comment by anatawa12** [comment]
治ったとする
