### ISSUE TITLE
Favourite button should be star rather than check box

### ISSUE THREAD

**Issue by lu-na-r** [vrc-get/vrc-get#740]
### Summary / 概要

Described in the title.

### Purpose / 目的

The current favourite selection style leads to misunderstanding. Users may regard the check box as a tool for multiple selection to edit or manage multiple projects simultaneously.

**Comment by anatawa12** [comment]
<img width="328" alt="image" src="https://github.com/vrc-get/vrc-get/assets/22656849/a1a42282-8e8a-42d5-b6e5-b44480a8e640">

こんな感じかな

**Comment by lu-na-r** [comment]
ありがとう！
