### ISSUE TITLE
パッケージの"すべて更新"を独立したボタンにする

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#754]
### Summary / 概要

よく使うものにも関わらず、サブメニューの中に入っており利用しづらいようです

> ・「全て更新」は普通にボタンとして置いてほしい
> （使用頻度が高いのに「メニュー→全て更新→適応」の3回操作を要求される）
> from: https://misskey.niri.la/notes/9rx6qaabtj

### Purpose / 目的

利便性の向上

**Comment by Sayamame-beans** [comment]
よく使うのは実際そうだと思うので(特にプロジェクトが幾つもある場合)、手間を減らせるように別途出した方が良いというのは確かに結構あるかも、とは思いますね

**Comment by anatawa12** [comment]
じゃぁ出すかぁ。

**Comment by Sayamame-beans** [comment]
> 幅的に出したら足りなそうという気もしたのですが

752のbulk用のボタンって常時表示ですか? 何かをチェックした時だけ表示ですか?
前者であれば、ここに一緒に入れる(選択してない時に全更新じゃないけど…なんかそんな感じで、同じ位置のボタンで役割を変えるか、別のボタンとして横に置いておくか)ことが出来そうな気がします?

**Comment by anatawa12** [comment]
> 752のbulk用のボタンって常時表示ですか? 何かをチェックした時だけ表示ですか?

チェックしたときのみです
