### ISSUE TITLE
The Project Menu Refused To Load with Errors if there is '.' in settings.json

### ISSUE THREAD

**Issue by Kare-Udon** [vrc-get/vrc-get#764]
### Description of the bug / バグの説明

I opened vrc-get-gui APP, and it throws the following errors.

```
2024-04-13T19:34:06.625681+08:00 [Error] vrc_get_vpm::unity_project: ProjectVersion.txt not found
2024-04-13T19:34:06.625625+08:00 [Error] vrc_get_vpm::unity_project: Packages directory not found
```

And the projects menu refuses to load.

I tried to delete the Unity projects imported before with editing the settings.json, but nothing changed.

### Steps to Reproduce / 再現手順

1. Open the APP
2. Meet this problem

### Expected Behavior / 想定される挙動

The projects menu loads.

### Screenshots / スクリーンショット

<img width="1112" alt="image" src="https://github.com/vrc-get/vrc-get/assets/52364111/77ac5fdb-cdc4-4c94-ba54-62d96b5db649">

### Software Version / バージョン情報

0.1.0-beta.19

### OS

macOS 14.4.1

### Additional context / 補足

Nice program! Thank you for your hard work~

**Comment by anatawa12** [comment]
The error is not as fatal error as refuse loading projects.
How many projects do you have in the settings.json?
Could you try removing vcc.litedb file?

**Comment by Kare-Udon** [comment]
> The error is not as fatal error as refuse loading projects. How many projects do you have in the settings.json? Could you try removing vcc.litedb file?

I may find the source of this issue.

There's a `'.'` path in `userProjects` list of `setting.json`, I have no idea how I added this path as a project. Maybe due to executing a wrong vpm command.

And this causes vcc-get-gui not finding config files and refuse to load the projects menu.

**Comment by anatawa12** [comment]
I reproduced this problem with adding '.' to settings.json. Thank you for root cause of this problem.
