### ISSUE TITLE
単一のウィンドウのみが開くようにする

### ISSUE THREAD

**Issue by Tliks** [vrc-get/vrc-get#774]
### Summary / 概要

現状では実行する度にウィンドウが増えていくが、既にウィンドウがある場合は追加で起動せず、既存のウィンドウを最前面に表示するような実装になってほしい。

### Purpose / 目的

複数のウィンドウが必要となるGUIではないと思うので、重複したウィンドウの起動を防げる。

**Comment by anatawa12** [comment]
参考: https://github.com/tauri-apps/plugins-workspace/blob/v1/plugins/single-instance/
