### ISSUE TITLE
チェックボックスにおけるホバーとクリックの範囲の不一致

### ISSUE THREAD

**Issue by Tliks** [vrc-get/vrc-get#796]
### Description of the bug / バグの説明

プロジェクトのfav機能および、パッケージの選択におけるチェックボックスで、マウスのホバー効果と実際のクリック可能な範囲の間に不一致があるように見えます。
ホバー効果がカバーする範囲に対しクリックが反応する範囲が多少狭いため、クリックしたつもりなのに選択されていないことがたまにあります。不一致はパッケージの選択におけるチェックボックスの方が大きい印象です

### Steps to Reproduce / 再現手順

1. マウスをチェックボックスの端や境界に近い場所に移動
2. ホバー効果があることを確認
3. クリックして何も起こらない

### Expected Behavior / 想定される挙動

チェックボックスの付近におけるホバー効果がある状態のクリックは必ず実行される

### Software Version / バージョン情報

0.1.0-beta.21

### OS

Windows 11 Home

**Comment by anatawa12** [comment]
多分フレームワーク入れ替えたときに関係なくなってるので閉じます
