### ISSUE TITLE
更新通知のダイアログでもう少し詳細に更新内容に触れて欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#806]
### Summary / 概要

現状、https://github.com/vrc-get/vrc-get/blob/master/CHANGELOG-gui.md を見に行かないと更新内容を全く把握することができません。
主要な更新内容をダイアログかALCOM上にページを用意する形で見られるようにして欲しい気がします。
(後者の場合、ダイアログの代わりにこのページを表示する形でも通知代わりになりそうですね…?)

### Purpose / 目的

更新内容が伝わりやすくなる

### Additional context / 補足

こうなると、日本語changelogも書いた方が良いか…(私が)

**Comment by anatawa12** [comment]
tauri標準の更新ダイアログだと言語分けできないのでもしやるなら更新ダイアログの内製から(これをやるための仕組みはあるっぽい)

**Comment by anatawa12** [comment]
これ翻訳作るの結構辛いな

**Comment by anatawa12** [comment]
英語だけで良い？

**Comment by Sayamame-beans** [comment]
まあ無いよりは…?

**Comment by anatawa12** [comment]
方法としてはchanges.txt作ってその内容を突っ込むかなぁ
