### ISSUE TITLE
アプリケーション上からBug報告やFeatureRequestをする導線が無い

### ISSUE THREAD

**Issue by meronmks** [vrc-get/vrc-get#807]
### Summary / 概要

ALCOMのアプリケーション上からIssuesページへのリンクが設定画面の一番下とかにあるとよさそう。

### Purpose / 目的

バグ報告や機能リクエストのハードルが多少下がる ~~（Githubの時点で高いというのは一旦置いておいて）~~

**Comment by anatawa12** [comment]
issue formの機能としてバージョンや環境を事前に書いておく事もできるしあったほうが良さそう

**Comment by Spokeek** [comment]
バージョン番号ボタンの下に問題を事前に入力するボタンはどうでしょうか?

- タイトルのバグ - [記入]
- タグ: バグ
- 説明：
【バグの簡単な説明】
バージョン：
x.x.x 言語: x.x.x

**Comment by anatawa12** [comment]
GitHub issuesにバージョンとOS情報だけ埋めて飛ぶだけにしたいかなぁ
