### ISSUE TITLE
ログが上が新しいの分かりづらいから戻したい (css/js力不足)

### ISSUE THREAD

**Issue by anatawa12** [vrc-get/vrc-get#809]
### Summary / 概要

ログが上が新しいの分かりづらいから戻したい

けどスクロール位置を適切に維持したままのstick to bottomの正しい方法がわからなくてできてない

### Purpose / 目的

ログが上が新しいの分かりづらいから戻したい

**Comment by anatawa12** [comment]
Note: Unity migrtionページでは追加される事に一番下にscroll してるけど、logsでは上の方見てる間はscroll to bottom しないようにしたい

**Comment by Spokeek** [comment]
最終的に何を聞かれているのかわからないのですが、もしかしたら訳がわからなくなっているのかもしれません。

新しいログを一番下に表示し、新しいログが到着すると自動的にスクロールするようにする必要があるのでしょうか？
