### ISSUE TITLE
メニューの順番

### ISSUE THREAD

**Issue by lu-na-r** [vrc-get/vrc-get#813]
### Summary / 概要

日本語で失礼します。現在、メニューの順番が、"Projects" → "Settings" → "VPM Repositories" → "Logs"となっていると思いますが、"Settings"と"VPM Repositories"の順番を入れ替えたほうがいいのではないか、というご提案です。

### Purpose / 目的

"Projects"と"VPM Repositories"はプロジェクト関連、"Settings"と"Logs"はALCOM関連なので、まとめたほうが分かりやすいのではないかと思いました。

### Additional context / 補足

現ユーザーが慣れた環境を変えるというデメリットもあるので、どのような意図で現在の順番になったかお伺いしたいです

**Comment by Spokeek** [comment]
その意図があったかどうかはわからない。
もしそれが確認されれば、変更するのは簡単だ。

**Comment by anatawa12** [comment]
順番に意味ないですね。

**Comment by Spokeek** [comment]
それなら、古いユーザーの利便性を考慮し、公式VCCの順番に合わせるのは問題ないと思う。
