### ISSUE TITLE
複数選択してパッケージをインストールする際に Upgraded all packages と通知が出る

### ISSUE THREAD

**Issue by kobi32768** [vrc-get/vrc-get#815]
### Description of the bug / バグの説明

表題のとおり
1つのみ選択でも出る

### Steps to Reproduce / 再現手順

1. プロジェクトの Manage packages 画面を開く
2. 左のチェックボックスから1つ以上の未インストールパッケージを選択する
3. Install Selected を押す
4. Upgraded all packages と通知が出る

### Expected Behavior / 想定される挙動

Upgraded all packages ではなく Installed all packages 等と通知が出る

### Software Version / バージョン情報

0.1.0

### OS

Windows 11 Pro 23H2

**Comment by Spokeek** [comment]
このユースケースは、チェックボックスを使用する際の一括操作全般に関するものだと思います。
インストールや削除を行うと、「すべてをアップグレードしました」というメッセージが表示されます。
私はコードを更新し、代わりに「Applied all changed in bulk」メッセージを使用するつもりです。
