### ISSUE TITLE
ウィンドウを最大化するとヘッダ幅がおかしくなる

### ISSUE THREAD

**Issue by kobi32768** [vrc-get/vrc-get#816]
### Description of the bug / バグの説明

Screenshots 欄参照
任意の画面で発生

### Steps to Reproduce / 再現手順

1. ウィンドウを最大化する

### Expected Behavior / 想定される挙動

下の他の要素と同じ幅になる

### Screenshots / スクリーンショット

![image](https://github.com/vrc-get/vrc-get/assets/40712426/4b913008-7e25-41d3-b823-a4bb095e5a92)

### Software Version / バージョン情報

0.1.0

### OS

Windows 11 Pro 23H2

**Comment by anatawa12** [comment]
Knownで #431 でついでに直してる最中
