### ISSUE TITLE
Document workflow for adding localization key and updating localization

### ISSUE THREAD

**Issue by anatawa12** [vrc-get/vrc-get#840]
Since this project has four languages, I could not maintain singer languages. Therefore, I have to define workflow for adding partially localized texts or others.

**Comment by anatawa12** [comment]
> Shouldn't translation keys that are missing in a language fallback to English?

I think missing keys should be fallback to English instead of localization key and it's already implemented.

> A channel to communicate new or changed keys to language maintainers would be neat.

I think github discussions can be used and I can make workflow to list-up missing keys.

Any suggestions are welcome.

**Comment by JustBuddy** [comment]
Sounds good to me.
I just need to know whenever there is a new/changed key to translate/adjust, and where that key is.

**Comment by anatawa12** [comment]
I have created action and tracking discussion for Japanese language #855.

I'm going to create similar discussion thread for other languages.

@JustBuddy @lonelyicer Could you check the Japanese version and could you let me know any ideas?

**Comment by JustBuddy** [comment]
Looks good, when I subscribe to that I should be notified whenever I need to do something.

**Comment by anatawa12** [comment]
> Looks good, when I subscribe to that I should be notified whenever I need to do something.

Thank you. I've created discussion for German #860

**Comment by lonelyicer** [comment]
> I have created action and tracking discussion for Japanese language #855.
> 
> I'm going to create similar discussion thread for other languages.
> 
> @JustBuddy @lonelyicer Could you check the Japanese version and could you let me know any ideas?

Sounds great.

**Comment by anatawa12** [comment]
> Sounds great.

Thank you. I've created discussion for Simplified Chinese #888

**Comment by anatawa12** [comment]
I've created discussion page for each localization and I've wrote the notes for adding localization keys and adding new languages so It's complete!

**Comment by lu-na-r** [comment]
Request "English Localization" forum too.

**Comment by lu-na-r** [comment]
As English is the fundamental language, there are no missing keys, but it is better to have a channel to discuss the better localisation.
