### ISSUE TITLE
Code Signing for Windows

### ISSUE THREAD

**Issue by anatawa12** [vrc-get/vrc-get#843]
### Summary / 概要

I want to sign ALCOM for Windows with Trusted Signing.

It's reasonably priced ($120/year).

### Purpose / 目的

We have to sign the ALCOM to not blocked by windows smartscreen.

### Additional context / 補足

https://learn.microsoft.com/azure/trusted-signing/overview

**Comment by anatawa12** [comment]
Related action: https://github.com/Azure/trusted-signing-action

**Comment by anatawa12** [comment]
Priority High

**Comment by anatawa12** [comment]
> Trusted Signing at this time can onboard only legal business entities that have verifiable tax history of three or more years. For a quicker onboarding process, ensure that public records for the legal business entity that you're validated are up to date.

https://learn.microsoft.com/en-us/azure/trusted-signing/quickstart?tabs=registerrp-portal%2Caccount-portal%2Ccertificateprofile-portal%2Cdeleteresources-portal#important-information-for-public-identity-validation

I'm not a legal business entity. I have to wait for relaxing this criteria

**Comment by anatawa12** [comment]
I'm considering other certificates for code Signing

**Comment by anatawa12** [comment]
Requirements:
- Cheap Enough
- Exportable Private Key for GitHub Actions

**Comment by anatawa12** [comment]
From list of certificate in MSDN (https://learn.microsoft.com/en-us/windows-hardware/drivers/dashboard/code-signing-cert-manage?redirectedfrom=MSDN)

(I did not check if they support certificate for personals)
Might be usable

- ssl.com: It supports Github Actions and other CI environments ([docs](https://www.ssl.com/guide/code-signing-automation/)) and relatively cheap (129USD = 20109JPY)
- DigiCert: It supports Github Actions ([docs](https://docs.digicert.com/es/software-trust-manager/ci-cd-integrations.html)) but expensive (44*12=528USD = 82336JPY)
- Enterust: not cheap 299USD = 46626JPY and GitHub Actions is officially supported ([action](https://github.com/EntrustCorporation/dvrenewal)).

It looks impossible to use
- certum: Cheapest (69EUR = 11696 JPY (w/HW token) or 49EUR = 8307JPY (cloud)) but impossible to use in GitHub Actions because it requires hardware token or custom software.
- Microsoft Azure Trusted Signing: It requires 3 years of business (120USD = 18711JPY)
- GlobalSign: USB Token is required and not cheap 60000 JPY
- IdenTrust: EV only? and HW Token is required and I could not find price publicly
- sectigo: HW Token required

**Comment by anatawa12** [comment]
Another consideration: should I add self-signed certificate instead if I choose not buying certificates?

**Comment by JustBuddy** [comment]
> Another consideration: should I add self-signed certificate instead if I choose not buying certificates?

Would that change behavior?
If it then just says that it can't verify the author instead of warning a user about a virus, this would be fine for now.

**Comment by ProffDea** [comment]
Is publishing to the microsoft store an option? It's free, microsoft will sign alcom for you, and it will provide the ability for alcom to be installed and updated via windows' package manager `winget` that I regularly use.

This reference is interesting:
https://gezihuzi.github.io/2024/04/05/publish-tauri-app-to-ms-store.html

https://learn.microsoft.com/en-us/windows/apps/distribute-through-store/how-to-distribute-your-win32-app-through-microsoft-store
![image](https://github.com/user-attachments/assets/6e218972-faf6-450f-afa8-afeb0fdcceb8)

**Comment by anatawa12** [comment]
I was planned to publish to winget registry soon but ms store might be ok

**Comment by anatawa12** [comment]
Thanks to sponsors, a few months after this issue was raised, I will be able to purchase a code signing certificate with the Github Sponsor's incomes. Thank you very much.

I will contact the issuer's support and confirm if I can use it with GitHub Actions and Tauri.
