### ISSUE TITLE
Discussion Channel

### ISSUE THREAD

**Issue by Dog** [vrc-get/vrc-get#853]
### Summary / 概要

I think it’d be great if there was some form of discussion channel for this project such as Discord

### Purpose / 目的

I believe this would potentially ease onboarding contributors and potentially answering small questions before an issue is opened. It could also make it easier for people attempting to work on projects on Mac or Linux to talk with each other.

### Additional context / 補足

If such a channel already exists, I believe it should be added to the readme and contributor guidelines.

**Comment by anatawa12** [comment]
How about github discussions? it's github-builtin discussion channel.

**Comment by anatawa12** [comment]
I have enabled github discussions: https://github.com/vrc-get/vrc-get/discussions
