### ISSUE TITLE
maximize保存されない

### ISSUE THREAD

**Issue by Tliks** [vrc-get/vrc-get#891]
### Description of the bug / バグの説明

related to #773
windows上では依然として保存されてないように見えます

### Steps to Reproduce / 再現手順

1. 全画面表示にする
2. 終了する
3. 起動して全画面表示になっていない

### Expected Behavior / 想定される挙動

保存される

### Software Version / バージョン情報

0.1.0

### OS

Windows 11 Home

**Comment by anatawa12** [comment]
全画面(fullscreen)ではなくmaximizeっぽいかも

**Comment by anatawa12** [comment]
is_maximizedで取れなさそうなのでどうしたらいいかがわからん状態になった

**Comment by anatawa12** [comment]
maximizeについてtauriに報告投げたほうがいい気がしてきた

**Comment by anatawa12** [comment]
upstreamに投げるためのパッケージを作る
