### ISSUE TITLE
DiscussionsにEnglish Localisationチャンネルを作って欲しい

### ISSUE THREAD

**Issue by lu-na-r** [vrc-get/vrc-get#892]
当然、Missing Keyはないけど、better localisationを議論できる場が欲しいです

**Comment by lu-na-r** [comment]
あと、Englishのmaintainerが誰かも知りたい

**Comment by anatawa12** [comment]
確かにあっていいですね

> Maintainer

明確にはなくてコードと一緒に私がやってますが英語圏の人に見てもらったほうがいいとも思ってます

**Comment by lu-na-r** [comment]
とりあえず、Discussionはたてて欲しいかな

**Comment by anatawa12** [comment]
今スマホなのでPC戻ったらやります

**Comment by Sayamame-beans** [comment]
> 明確にはなくてコードと一緒に私がやってますが

あとは私も少し手を出してましたっけ…?

**Comment by lu-na-r** [comment]
ってことは、あなたわさんとさやまめさんがmaintainerか

**Comment by anatawa12** [comment]
#894 をはやしました
