### ISSUE TITLE
Need for french translation ?

### ISSUE THREAD

**Issue by Spokeek** [vrc-get/vrc-get#895]
### Summary / 概要

Well, title is self explanatory. I'm French native so i can do that translation. But i'm unsure if there is a need for it.

### Purpose / 目的

More appeal for French users.

**Comment by anatawa12** [comment]
I think having more localization will increase merits of ALCOM so adding localization is very welcome!

**Comment by Spokeek** [comment]
> I think having more localization will increase merits of ALCOM so adding localization is very welcome!

Feel free to add a discussion if required, i'll base my work on the english translation then.

**Comment by anatawa12** [comment]
Because of design in my workflow, I could not add to the action unless we have so could you create pr first?

**Comment by Spokeek** [comment]
Done @anatawa12
