### ISSUE TITLE
翻訳ファイル内の行を並べ替える

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#923]
現時点では、各文章が出てくる順番で並んでいるような形になっていますが、これをページ単位などで並べ替えることを検討しています。
並べ替えの際は、(json的に問題無いはずなので)空行を挟んで分かりやすくするつもりです。

("projects"ページのものはここに纏まっていて、"settings"ページのものはここに纏まっていて…という感じにします。キー自体には変更を加えません。)

**Comment by JustBuddy** [comment]
はい、ぜひ試してみてください。
すべての翻訳キーが整理され、カテゴリごとに少し分けられていると、それらを使う際に非常に役立ちますね。

Yes please.
Having all translation keys sorted, and a bit separated by category or page would immensely help to work with them.

**Comment by Sayamame-beans** [comment]
途中までやってたのがあったのですが、キー増えてて合流が厳しいので今度もう一回やり直します…
