### ISSUE TITLE
Show a toast for "Check for updates" button when there is no update

### ISSUE THREAD

**Issue by lu-na-r** [vrc-get/vrc-get#926]
### Summary / 概要

Currently, when you click "Check for updates" button in settings menu with no updates provided, there is no response.
If ALCOM is the latest version, a toast such as "ALCOM is up to date." or "There is no update." or "You are using the newest version of ALCOM." should be appear.

### Purpose / 目的

Users can explicitly recognise that they are using the newest version.

**Comment by anatawa12** [comment]
https://github.com/vrc-get/vrc-get/pull/762#issuecomment-2051862990

>> 更新がなく最新であったことを示すトーストかダイアログがあった方が良さそうです
> 
> 知る限りできないからこの実装になってる

**Comment by lu-na-r** [comment]
できないんだ、知らなかった。duplicateで申し訳ない
