### ISSUE TITLE
2022.3.22f1 has been promoted to stable since 3.6.0

### ISSUE THREAD

**Issue by JustBuddy** [vrc-get/vrc-get#927]
### Summary / 概要

2022.3.22f1 is now the used unity version since 3.6.0, the version changer is currently not implemented.

### Purpose / 目的

Provide an update path to 2022.3.22f1

### Additional context / 補足

```
Unity Version Upgrade
With this change, we now officially support Unity version 2022.3.22f1! Don't worry, the currently recommended .6f1 version will continue to work for a while to come.

We'd still encourage you to give the upgrade a try - we haven't seen any issues upgrading projects so far, and the new VCC version will guide you through the upgrade start-to-finish!
```

**Comment by anatawa12** [comment]
The system to upgrade unity 2022 patch version has been implemented in #863 (issue: #842) and I have created the PR upgrade recommended unity 2022 patch version (#928)!
