### ISSUE TITLE
ログのタブが使えない

### ISSUE THREAD

**Issue by Uttu209** [vrc-get/vrc-get#943]
### Description of the bug / バグの説明

ログのタブを開いてもわたしの環境下ではログを表示する欄が表示されません。

### Steps to Reproduce / 再現手順

ログタブを押す

### Expected Behavior / 想定される挙動

ログ表示の欄が表示される

### Screenshots / スクリーンショット

<img width="1661" alt="スクリーンショット 2024-05-11 18 46 28" src="https://github.com/vrc-get/vrc-get/assets/145257547/c5c64743-b14e-435a-92f7-f95a8a0690fe">

### Software Version / バージョン情報

0.1.2

### OS

Darwin - darwin - 12.7.4 - aarch64

### Additional context / 補足

これまでにリリースされた全てのバージョンでこうなっていました。

**Comment by anatawa12** [comment]
ログファイル自体は生成されていますか？

**Comment by Uttu209** [comment]
いま探してみました。 vrc-get-logs のフォルダ内のものでしたらちゃんと生成されていそうです。

**Comment by anatawa12** [comment]
[toReversed](https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/toReversed)が古いmacOSだと動かないのでこれが原因かもしれない
