### ISSUE TITLE
プロジェクトと対応するUnityが存在しない場合、それがVRCの推奨バージョンであればトーストではなく導入誘導ダイアログにして欲しい

### ISSUE THREAD

**Issue by Sayamame-beans** [vrc-get/vrc-get#944]
### Summary / 概要

しっかりとした導入ダイアログは未実装ですが、現時点でも2022.3.22f1の導入ダイアログは存在します(2022.3.6f1からのpatch migration時)
しかし、既存のプロジェクトや新規作成したプロジェクトは2022.3.22f1が入っていなくても、2022.3.22f1向けとして作成されてしまうこと、ALCOMにプロジェクトを開くUnityバージョンを選択する機能が未実装なことが重なり、トーストで対応バージョンが存在しない旨だけが表示されてしまいます。

そのため、プロジェクトと対応するUnityバージョンが存在せず、それがVRC推奨バージョンである場合は、導入ダイアログを表示するようにして欲しいです。

### Purpose / 目的

既存の仕様だとちょっと不便

**Comment by anatawa12** [comment]
ProjectVersion.txtが正しければrecommended関係なくunityhub呼べそう
