### ISSUE TITLE
Localized with Crowdin (Crowdin In Context)

### ISSUE THREAD

**Issue by Misaka-L** [vrc-get/vrc-get#948]
### Summary / 概要

Use Crowdin to localize ALCOM.

### Purpose / 目的

It will enable translators to contribute to localization easily (without figuring out how to use git and edit .json5 files). Additionally, it allows the use of Crowdin In Context feature, making previewing localization easier.

### Additional context / 補足

I make a simple implementation of Crowdin & Crowdin In Context integration.

![GIF 2024-5-12 上午 12-36-38](https://github.com/vrc-get/vrc-get/assets/42287372/f593b1ae-ad56-4f68-b451-53633ba35c41)

**Comment by Misaka-L** [comment]
https://github.com/Misaka-L/vrc-get/tree/feature-crowdin-crowdin

**Comment by anatawa12** [comment]
I researched about crowdin before and as far as I found, commit author will become single bot user so I choose to use manual updates.
I think it's important to keep author information in git history.

Is there any workaround for this problem in crowdin?

**Comment by Misaka-L** [comment]
> I researched about crowdin before and as far as I found, commit author will become single bot user so I choose to use manual updates. I think it's important to keep author information in git history.
> 
> Is there any workaround for this problem in crowdin?

I think it can be done with [github commit co-authors](https://docs.github.com/zh/pull-requests/committing-changes-to-your-project/creating-and-editing-commits/creating-a-commit-with-multiple-authors).

We can set up a github action workflow using [crowdin-action](https://github.com/marketplace/actions/crowdin-action#git-and-pull-request-options) and include `Co-authored-by: NAME <NAME@EXAMPLE.COM>` in the commit message. (This can also assign the translator to the pull request or mention them in pull request)

**Comment by anatawa12** [comment]
it looks crowdin-action and crowdin github app does not have feature to retrieve authors of the localization from crowdin, isn't it?

**Comment by Misaka-L** [comment]
> it looks crowdin-action and crowdin github app does not have feature to retrieve authors of the localization from crowdin, isn't it?

Yes... but the members info can be fetch from crowdin api: https://developer.crowdin.com/api/v2/#operation/api.projects.members.getMany

**Comment by anatawa12** [comment]
Umm.. what i want to keep on git is who changed that changes.
it's not what i want.

According to tag of crowdin/github-action#35, it's api limitation in crowdin so It looks it's hard to use crowdin.

**Comment by Misaka-L** [comment]
> Umm.. what i want to keep on git is who changed that changes. it's not what i want.
> 
> According to tag of [crowdin/github-action#35](https://github.com/crowdin/github-action/issues/35), it's api limitation in crowdin so It looks it's hard to use crowdin.

Crowdin probide a activity feature make track who contribute to localization possible.

![image](https://github.com/vrc-get/vrc-get/assets/42287372/f0cb6e4d-03d2-4c11-b5f2-4eaead60a174)

But it only provide in web app. (unless use crowdin web api which is not public)

![image](https://github.com/vrc-get/vrc-get/assets/42287372/717cb0ce-5629-4e57-aaeb-de5ae77c67d0)

**Comment by Misaka-L** [comment]
I will be busy this week. So maybe I can only reply you at next weenend. sorry for that....

**Comment by anatawa12** [comment]
I don't like to call internal api.
Therefore, I don't use crowdin due to lack of features, for now.

According to https://github.com/crowdin/github-action/issues/35#issuecomment-769783756, weblate supports that so we may use self-hosted or libre plan of weblate in the future but not soon.
