### ISSUE TITLE
Needs switch fonts funtion

### ISSUE THREAD

**Issue by lonelyicer** [vrc-get/vrc-get#968]
### Summary / 概要

Needs switch fonts funtion

### Purpose / 目的

The fonts are using now will make the fonts not conform to the common writing style of the language when displaying other languages.
e.g. Simplified Chinese

### Additional context / 補足

“经”
Displayed in ALCOM (Title)
![image](https://github.com/vrc-get/vrc-get/assets/63995099/ded3e4c1-59c9-4abc-b9bd-2d2ca048a1d4)

Common writing style
![image](https://github.com/vrc-get/vrc-get/assets/63995099/1950c0f6-37c2-498b-90c1-ac6cdd049573)

**Comment by anatawa12** [comment]
Oh, sorry I forget ideographs are unified in unicode. 

we have several options and we can combine 

- change font based on locale\
  the current font Noto Sans already has glyph so I believe this is not necessary.
- we may fix with adding lang tag to html element. I hope this will work.
- we may use ideograph variant selectors for localized chars but it doesn't work for user nput so I dont like.

However, it looks '径' is different char than '经' in unicode (different left side of ideograph) so it might be mistake in localization database? 

https://glyphwiki.org/wiki/u7ecf
https://glyphwiki.org/wiki/u5f84

![image](https://github.com/vrc-get/vrc-get/assets/22656849/41bae8b7-cb4a-4e7d-a695-02038fa1cf07)

**Comment by anatawa12** [comment]
Unfortunately, I could not find way to change default glyph based on locale, I selected using system fronts instead of bundling.
