### ISSUE TITLE
既にプロジェクトを開いている場合、OPENを押しても開けないようにしてほしい

### ISSUE THREAD

**Issue by lu-na-r** [vrc-get/vrc-get#982]
### Summary / 概要

タイトルの通り

### Purpose / 目的

OPENを押す際、誤ってマウスが2回押ささることがあり、Unityで複数インスタンスのエラーが表示されてしまう。ALCOM側で、既にプロジェクトを開いていることを検知して警告を出し、プロジェクトを開けないような仕組みがあれば便利だと思う。

**Comment by anatawa12** [comment]
macOSにおいては`Temp/UnityLockFile`を`F_GETLK`してlockがあるかどうかで判断できそう。
しかし二回押すときの速度で対応できるかは不明。crateは`nix`でどうにかなりそう

windowsもlockの確認で判断できそう。
