### ISSUE TITLE
Windows JP環境でmonospaceフォントがひどい

### ISSUE THREAD

**Issue by anatawa12** [vrc-get/vrc-get#985]
### Description of the bug / バグの説明

Windows JP環境でmonospaceフォントがひどい。

https://misskey.niri.la/notes/9te9gbd3u8
<img width="2016" alt="Screenshot 2024-05-17 at 22 15 00" src="https://github.com/vrc-get/vrc-get/assets/22656849/83b5ebea-1e8c-4ffb-ac30-e0c440a26abf">

### Steps to Reproduce / 再現手順

HEADのCIビルドをダウンロード

### Expected Behavior / 想定される挙動

もっとマシなアウトラインフォントで描画する

### Screenshots / スクリーンショット

<img width="2016" alt="Screenshot 2024-05-17 at 22 15 00" src="https://github.com/vrc-get/vrc-get/assets/22656849/83b5ebea-1e8c-4ffb-ac30-e0c440a26abf">

### Software Version / バージョン情報

0.1.4-beta.0+2eca57f

### OS

Windows 11

### Additional context / 補足

そもそもproject pathのようなユーザ入力部分をnon monospaceにしてmonospaceは英語フォントにするのは一つの案

**Comment by KisaragiEffective** [comment]
案: consolasあるいはCourier Newをfont-familyに設定する

**Comment by anatawa12** [comment]
ユーザインプットをmonospace影響下にするとフォント手動指定が辛いことになるので、禁じたい気もする。
